### ISSUE TITLE
2.7.4的版本上没有setAdapter的方法了吗

### ISSUE THREAD

**Issue by cloudmist** [zhpanvip/BannerViewPager#101]
2.7.4的版本上没有setAdapter的方法了吗

**Comment by zhpanvip** [comment]
最新现在master跟readme上是3.0的代码，但3.0版本还没来得及发布。你可以先切换到v2.x分支查看2.x版本的使用方法。

**Comment by cloudmist** [comment]
嗯，我现在依赖的2.7.4，然后点进去看BannerViewPager的源码，没有这个方法，不过把整个项目的源码下载下来看，是有的

**Comment by zhpanvip** [comment]
3.0的包已经打出来了，可以尝试3.0了

**Comment by cloudmist** [comment]
由于ViewPager2不支持Android support，因此BannerViewPager 3.0不再支持Android support，如果你仍在使用Android support请使用，请移步BannerViewPager 2.x版本

点击“BannerViewPager 2.x版本” 出现404

**Comment by cloudmist** [comment]
好的，我用用3.0版本

**Comment by cloudmist** [comment]
感谢
