### ISSUE TITLE
Error inflating class com.zhpan.bannerview.BannerViewPager

### ISSUE THREAD

**Issue by cloudmist** [zhpanvip/BannerViewPager#104]
使用3.0.0一开始是好的，然后会出现  Error inflating class com.zhpan.bannerview.BannerViewPager，是因为什么

**Comment by cloudmist** [comment]
![微信图片_20200408201734](https://user-images.githubusercontent.com/26298774/78783320-090c8880-79d6-11ea-9902-6a657e8dc743.png)

**Comment by zhpanvip** [comment]
你是怎么用的，代码方便贴一下吗

**Comment by cloudmist** [comment]
![1](https://user-images.githubusercontent.com/26298774/78846755-67218600-7a3f-11ea-9d7a-5d510ad02f2e.png)
![2](https://user-images.githubusercontent.com/26298774/78846756-68eb4980-7a3f-11ea-9ac5-fc6a48f8de50.png)

![3](https://user-images.githubusercontent.com/26298774/78846775-786a9280-7a3f-11ea-96c5-cb20608730d7.png)
![4](https://user-images.githubusercontent.com/26298774/78846784-802a3700-7a3f-11ea-9097-6061c6a5cc06.png)

**Comment by zhpanvip** [comment]
看不出来什么问题，是必现吗？可以加群详细说明一下问题。

**Comment by cloudmist** [comment]
是必现的，怎么加群啊？

**Comment by zhpanvip** [comment]
文档末尾有二维码

**Comment by cloudmist** [comment]
好的

**Comment by yxf1991** [comment]
遇到了相同的问题，
