### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by iBotasky** [zhpanvip/BannerViewPager#111]
今天偶然看到这个库，下下来看看，觉得还不错啊，运行代码首页有一个竖向滑动的ViewPagger的Banner，Indicator却是横向的，有点突兀，可以考虑适配一下Vertical的Indicator.

**Comment by zhpanvip** [comment]
目前Indicator已经单独拆出来了，链接地址https://github.com/zhpanvip/viewpagerindicator。后续我会在这个库上尝试扩展竖直。但是支持竖直就目前来说比较麻烦。

**Comment by iBotasky** [comment]
哈哈哈,我也只是个建议~，库本身还是蛮棒的，已经可以适用大部分场景了

**Comment by zhpanvip** [comment]
感谢支持
