### ISSUE TITLE
CoordinatorLayout+AppBarLayout滑动嵌套Banner会导致Banner消费了向上的滑动事件导致滑动不了

### ISSUE THREAD

**Issue by LDJHXM** [zhpanvip/BannerViewPager#115]
CoordinatorLayout+AppBarLayout布局  AppBarLayout里面有Banner  会导致手指在Banner区域不会向上下滑动 只会左右滑动  应该是banner内部滑动的时候消费掉了滑动事件?我需要继承重写一下么

**Comment by LDJHXM** [comment]
@zhpanvip

**Comment by zhpanvip** [comment]
如果banner是水平滑动的话内部是没有拦截竖直滑动的事件的。如果拦截了竖直滑动事件像下拉刷新的框架也会失效。对于配合coordinatorLayout跟AppbarLayout使用还没有尝试过。但是因为coordinator对于事件处理比较复杂可能会存在一些冲突情况。等我验证下看能不能适配修复一下。

**Comment by LDJHXM** [comment]
看了一下源码 是在onInterceptTouchEvent里面做了一些滑动的判断 我继承重写onInterceptTouchEvent返回false就行了 但是这样的话只有0度角水平滑动才会触发 类似斜着滑动(角度很小)也只会上下滑动了  不过刚好满足我的需求~ 看起来这样不会有什么问题 @zhpanvip

**Comment by zhpanvip** [comment]
onInterceptTouchEvent并没有去拦截竖直事件，这个事件有可能被点击事件消费掉了？你这么处理后看下点击事件还有用吗？

**Comment by LDJHXM** [comment]
有用  我重写onInterceptTouchEvent返回false的话就能竖直滑动 没做任何处理的话在banner区域内竖直滑动就失效了(斜着滑动变成了左右滑动)  是因为getParent().requestDisallowInterceptTouchEvent(true)这行代码禁止掉了父布局拦截该事件导致的 你有空可以试一下 @zhpanvip

**Comment by LDJHXM** [comment]
不做任何处理的话垂直滑动在banner区域内松开会触发点击事件 应该是点击事件消费掉了？

**Comment by KAICW** [comment]
同样遇到这个问题，解决办法也是拦截

**Comment by GoldDreams** [comment]
确实会有这个问题，我也遇到了，直接导致在banner上，向上滑动无效，然后AppBarLayout无法滑动。模仿楼上拦截下就好了。
eg:
public class MyBannerViewPager<T, VH extends BaseViewHolder<T>> extends BannerViewPager<T, VH> {
    public MyBannerViewPager(Context context) {
        super(context);
    }

    public MyBannerViewPager(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public MyBannerViewPager(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        return false;
    }
}

**Comment by zhpanvip** [comment]
> 确实会有这个问题，我也遇到了，直接导致在banner上，向上滑动无效，然后AppBarLayout无法滑动。模仿楼上拦截下就好了。
> eg:
> public class MyBannerViewPager<T, VH extends BaseViewHolder> extends BannerViewPager<T, VH> {
> public MyBannerViewPager(Context context) {
> super(context);
> }
> 
> ```
> public MyBannerViewPager(Context context, AttributeSet attrs) {
>     super(context, attrs);
> }
> 
> public MyBannerViewPager(Context context, AttributeSet attrs, int defStyleAttr) {
>     super(context, attrs, defStyleAttr);
> }
> 
> @Override
> public boolean onInterceptTouchEvent(MotionEvent ev) {
>     return false;
> }
> ```
> 
> }

onInterceptTouchEvent直接返回false会屏蔽掉对滑动冲突的处理，在某些存在滑动冲突的情况下会出现问题。这个问题应该是BVP在处理Down事件时禁止了父View拦截事件引起的。回头有时间看下，应该可以优化处理。

**Comment by weikaiyun** [comment]
请问这个问题解决了吗

**Comment by GoldDreams** [comment]
按照我上面给出的代码可以暂时解决滑动的问题，后面的工作等大佬优化咯




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "weikaiyun"<notifications@github.com&gt;; 
发送时间: 2020年7月7日(星期二) 中午11:24
收件人: "zhpanvip/BannerViewPager"<BannerViewPager@noreply.github.com&gt;; 
抄送: "731618209"<731618209@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [zhpanvip/BannerViewPager] CoordinatorLayout+AppBarLayout滑动嵌套Banner会导致Banner消费了向上的滑动事件导致滑动不了 (#115)





 
请问这个问题解决了吗

**Comment by weikaiyun** [comment]
> 按照我上面给出的代码可以暂时解决滑动的问题，后面的工作等大佬优化咯
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "weikaiyun"<notifications@github.com&gt;; 发送时间: 2020年7月7日(星期二) 中午11:24 收件人: "zhpanvip/BannerViewPager"<BannerViewPager@noreply.github.com&gt;; 抄送: "731618209"<731618209@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [zhpanvip/BannerViewPager] CoordinatorLayout+AppBarLayout滑动嵌套Banner会导致Banner消费了向上的滑动事件导致滑动不了 (#115) 请问这个问题解决了吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

可是这样屏蔽了 好多库里面的内部操作 没有问题吗

**Comment by GoldDreams** [comment]
你可以先尝试一下咯，我这边这样使用还没有发现！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "weikaiyun"<notifications@github.com&gt;; 
发送时间: 2020年7月7日(星期二) 中午1:42
收件人: "zhpanvip/BannerViewPager"<BannerViewPager@noreply.github.com&gt;; 
抄送: "731618209"<731618209@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [zhpanvip/BannerViewPager] CoordinatorLayout+AppBarLayout滑动嵌套Banner会导致Banner消费了向上的滑动事件导致滑动不了 (#115)





  
按照我上面给出的代码可以暂时解决滑动的问题，后面的工作等大佬优化咯
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "weikaiyun"<notifications@github.com&gt;; 发送时间: 2020年7月7日(星期二) 中午11:24 收件人: "zhpanvip/BannerViewPager"<BannerViewPager@noreply.github.com&gt;; 抄送: "731618209"<731618209@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [zhpanvip/BannerViewPager] CoordinatorLayout+AppBarLayout滑动嵌套Banner会导致Banner消费了向上的滑动事件导致滑动不了 (#115) 请问这个问题解决了吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
可是这样屏蔽了 好多库里面的内部操作 没有问题吗

**Comment by weikaiyun** [comment]
好的 有时间我把这个库的源代码完整过一遍

**Comment by weikaiyun** [comment]
> > 确实会有这个问题，我也遇到了，直接导致在banner上，向上滑动无效，然后AppBarLayout无法滑动。模仿楼上拦截下就好了。
> > eg:
> > public class MyBannerViewPager<T, VH extends BaseViewHolder> extends BannerViewPager<T, VH> {
> > public MyBannerViewPager(Context context) {
> > super(context);
> > }
> > ```
> > public MyBannerViewPager(Context context, AttributeSet attrs) {
> >     super(context, attrs);
> > }
> > 
> > public MyBannerViewPager(Context context, AttributeSet attrs, int defStyleAttr) {
> >     super(context, attrs, defStyleAttr);
> > }
> > 
> > @Override
> > public boolean onInterceptTouchEvent(MotionEvent ev) {
> >     return false;
> > }
> > ```
> > 
> > 
> > }
> 
> onInterceptTouchEvent直接返回false会屏蔽掉对滑动冲突的处理，在某些存在滑动冲突的情况下会出现问题。这个问题应该是BVP在处理Down事件时禁止了父View拦截事件引起的。回头有时间看下，应该可以优化处理。

版主 啥时候能优化这个问题呀

**Comment by zhpanvip** [comment]
> > > 确实会有这个问题，我也遇到了，直接导致在banner上，向上滑动无效，然后AppBarLayout无法滑动。模仿楼上拦截下就好了。
> > > eg:
> > > public class MyBannerViewPager<T, VH extends BaseViewHolder> extends BannerViewPager<T, VH> {
> > > public MyBannerViewPager(Context context) {
> > > super(context);
> > > }
> > > ```
> > > public MyBannerViewPager(Context context, AttributeSet attrs) {
> > >     super(context, attrs);
> > > }
> > > 
> > > public MyBannerViewPager(Context context, AttributeSet attrs, int defStyleAttr) {
> > >     super(context, attrs, defStyleAttr);
> > > }
> > > 
> > > @Override
> > > public boolean onInterceptTouchEvent(MotionEvent ev) {
> > >     return false;
> > > }
> > > ```
> > > 
> > > 
> > > }
> > 
> > 
> > onInterceptTouchEvent直接返回false会屏蔽掉对滑动冲突的处理，在某些存在滑动冲突的情况下会出现问题。这个问题应该是BVP在处理Down事件时禁止了父View拦截事件引起的。回头有时间看下，应该可以优化处理。
> 
> 版主 啥时候能优化这个问题呀 请问新版本什么时候可以出呢

下个版本应该会修复

**Comment by zhpanvip** [comment]
3.1.4已修复

**Comment by itdais** [comment]
使用 CoordinatorLayout+NestedScrollView+BannerViewPager 还是会出现滑动问题，仅滑动了下方试图，这个在3.1.4中还是没有解决

**Comment by zhpanvip** [comment]
> 使用 CoordinatorLayout+NestedScrollView+BannerViewPager 还是会出现滑动问题，仅滑动了下方试图，这个在3.1.4中还是没有解决
测试的RecyclerView已经没问题了呀

**Comment by zhpanvip** [comment]
> 使用 CoordinatorLayout+NestedScrollView+BannerViewPager 还是会出现滑动问题，仅滑动了下方试图，这个在3.1.4中还是没有解决

现在sample中首页已经改成CoordinatorLayout+AppBarLayout了，你可以下载demo查看。现在是没有问题的

**Comment by itdais** [comment]
@zhpanvip 不是，demo中使用的AppBarLayout包裹BannerViewPager,而我这边使用的是CoordinatorLayout+ AppBarLayout+ NestedScrollView,使用NestedScrollView包裹的BannerViewPager出现滑动问题,目前我是用其他方法解决的.

**Comment by weikaiyun** [comment]
> @zhpanvip 不是，demo中使用的AppBarLayout包裹BannerViewPager,而我这边使用的是CoordinatorLayout+ AppBarLayout+ NestedScrollView,使用NestedScrollView包裹的BannerViewPager出现滑动问题,目前我是用其他方法解决的.

我也碰到问题了 你是咋解决的呀

**Comment by zhpanvip** [comment]
> > @zhpanvip 不是，demo中使用的AppBarLayout包裹BannerViewPager,而我这边使用的是CoordinatorLayout+ AppBarLayout+ NestedScrollView,使用NestedScrollView包裹的BannerViewPager出现滑动问题,目前我是用其他方法解决的.
> 
> 我也碰到问题了 你是咋解决的呀

最新版本需要调用BVP的disallowInterceptTouchEvent方法。

**Comment by zgmd** [comment]
CoordinatorLayout+ NestedScrollView + banner 还是有问题disallowInterceptTouchEvent 这个方法无法解决冲突

**Comment by zgmd** [comment]
recyclerview.setNestedScrollingEnabled(false) 可以解决ry的冲突问题

**Comment by AnyLifeZLB** [comment]
> [@zhpanvip](https://github.com/zhpanvip) 不是，demo中使用的AppBarLayout包裹BannerViewPager,而我这边使用的是CoordinatorLayout+ AppBarLayout+ NestedScrollView,使用NestedScrollView包裹的BannerViewPager出现滑动问题,目前我是用其他方法解决的.

我也遇到这问题，怎么解决的？
