### ISSUE TITLE
FigureIndicatorView

### ISSUE THREAD

**Issue by Joker-Jun** [zhpanvip/BannerViewPager#116]
使用demo中自定义设置这个后，数字变化时快时慢，有时候在最后4到1时，乱跳

**Comment by zhpanvip** [comment]
你看下你是不是设置了indicatorSlideMode了？如果设置成SMOOTH或者WORM是会出现这样的情况的。去掉或者改成NORMAL就行了。

**Comment by Joker-Jun** [comment]
是的，经测试关闭即可。
