### ISSUE TITLE
使用glide的 CenterCrop和RoundedCorners 2个transform 展示图片 圆角显示问题

### ISSUE THREAD

**Issue by chenenqiang12345** [zhpanvip/BannerViewPager#117]
急急急！使用glide的 CenterCrop和RoundedCorners 2个transform 展示图片 圆角显示问题

**Comment by zhpanvip** [comment]
请先确定是不是你自身使用存在问题，因为你图片比例跟ImageView比例相差较大时使用centercrop模式用gilde转换圆角本身就会有问题。

**Comment by chenenqiang12345** [comment]
我用 recycler 没问题啊 结合你的 就有问题

**Comment by chenenqiang12345** [comment]
第一张 裁剪正常 后面都不正常

**Comment by zhpanvip** [comment]
如果你现在项目minSDK大于等于21，你可以先常使用sample中的CornerImageView去实现圆角。你反馈的这个问题我需要去验证一下。

**Comment by chenenqiang12345** [comment]
![image](https://user-images.githubusercontent.com/22112302/80663167-d41bbf00-8ac5-11ea-9109-48c650e057c2.png)
![image](https://user-images.githubusercontent.com/22112302/80663191-e3027180-8ac5-11ea-843e-901b908713db.png)
第一场正常 后面都不行

**Comment by chenenqiang12345** [comment]
![1588210558](https://user-images.githubusercontent.com/22112302/80663271-18a75a80-8ac6-11ea-8117-15195412986d.png)
![1588210558](https://user-images.githubusercontent.com/22112302/80663276-1ba24b00-8ac6-11ea-99c5-0bb488dcda64.jpg)

**Comment by zhpanvip** [comment]
你这个问题看起来这个跟BannerViewPager没关系，是Glide的问题。图片宽高比跟ImageView宽高比相差比较大。你可以换张图片试试看。

**Comment by chenenqiang12345** [comment]
我一开始 用 你的 不知道 哪个版本没问题， 后来 更新 后出的问题

**Comment by zhpanvip** [comment]
你现在用的2.x版本还是3.x版本？

**Comment by chenenqiang12345** [comment]
我先在用的 最新的 之前 不知道 哪个 没问题 所以 你可以试下

**Comment by zhpanvip** [comment]
ImageView的scaleType设置成centerCrop是会出现你说的这个问题，设置成FitXY就是正常的。你可以试一下。这个问题确实不是BVP的问题。

**Comment by chenenqiang12345** [comment]
我已经确定是你的 这个有问题了，我用了别的 图片框架依然有问题，用别人的 轮播图 没有
