### ISSUE TITLE
[v_2.x] 如何实现一屏多页+自定义PageTransformer

### ISSUE THREAD

**Issue by XF-zhjnc** [zhpanvip/BannerViewPager#118]
例如我想实现Win PC 端网易云音乐首页的轮播banner，但是发现没有暴露足够的api用于实现一屏多页的效果，参照下面方法我初步实现了该效果的PageTransformer，想问作者是否有我没注意到的api可以实现一屏多页+自定义PageTransformer的？ 
 https://github.com/zhpanvip/BannerViewPager/blob/017c7b39816069588864c185d60542ca0cbbeeee/bannerview/src/main/java/com/zhpan/bannerview/BannerViewPager.java#L327

**Comment by zhpanvip** [comment]
目前一屏多页仅支持通过setMultiPageStyle方式实现，后续版本我会尝试做些改动来支持自定义的PageTransformer实现一屏多页。

**Comment by XF-zhjnc** [comment]
thx!

**Comment by zhpanvip** [comment]
在3.1.1版本中针对这个问题做了些优化，通过setRevealWidth方法即可实现一屏三页，同时可以通过addPageTransformer或者setPageTransformer设置一屏三页的页面动画。
