### ISSUE TITLE
底部Tab的Fragment，里面RecycleView里面有个Item 是Banner，切换时Fragment怎么调用stopLoop（）？

### ISSUE THREAD

**Issue by goodsfile** [zhpanvip/BannerViewPager#119]
@zhpanvip

**Comment by zhpanvip** [comment]
stopLoop并不是必须要调用的

**Comment by goodsfile** [comment]
如果想切换页面 想让它停止 该怎么做了？

**Comment by goodsfile** [comment]
@zhpanvip

**Comment by zhpanvip** [comment]
> 如果想切换页面 想让它停止 该怎么做了？

切换页面BVP是会自动停止轮播的

**Comment by goodsfile** [comment]
@zhpanvip 我在其他页面 BVP 还是照样会轮播，并不会 因为切换页面停止

**Comment by zhpanvip** [comment]
没想到有比较好的解决方案。不过即使不掉用stop也不会造成内存泄漏的。你可以自己探究一下有没有好的解决办法。

**Comment by zhpanvip** [comment]
3.1.5版本已支持通过setLifecycleRegistry来控制。
