### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by asjqkkkk** [zhpanvip/BannerViewPager#12]
现在想拿到当前页面的position，但是currentPosition是private的，还请作者写一个get方法，把它暴露出来😊

**Comment by asjqkkkk** [comment]
比如我想通过按钮的方式，手动去进行上一页或者下一页的跳转，拿不到currentPosition就没有办法

**Comment by zhpanvip** [comment]
将在2.3.5版本中添加，同时会添加setCurrentItem(int item)接口。

**Comment by asjqkkkk** [comment]
> 将在2.3.5版本中添加，同时会添加setCurrentItem(int item)接口。

Waiting for you😂

**Comment by zhpanvip** [comment]
2.3.5 release已发布
