### ISSUE TITLE
设置了自定义Indicator后就无法切换为自带的模式了

### ISSUE THREAD

**Issue by hanzhifengyun** [zhpanvip/BannerViewPager#120]
isCustomIndicator没有设置为false的入口，如果把banner放在list里面，如果有两种不同样式的Indicator，复用性会有问题

**Comment by zhpanvip** [comment]
是的，确实会存在自定义指示器跟自有指示器冲突的问题。但是iscustomindicator并不方便对外开放出来。解决办法你可以参考sample的OthersFragment.即都使用自定义指示器即可。

**Comment by zhpanvip** [comment]
确保你使用的是最新版本。

**Comment by zhpanvip** [comment]
Issue先关掉了，如果仍然有问题可以Reopen。
