### ISSUE TITLE
请问缩放模式下如何能够实现点击最后一个item平滑居中呢？

### ISSUE THREAD

**Issue by interfans** [zhpanvip/BannerViewPager#121]
<img width="425" alt="F4BFFECE-20D2-4F16-9DED-1953E8A446E2" src="https://user-images.githubusercontent.com/31506972/81466498-c2909080-9204-11ea-8386-5710ce893ade.png">

现在遇到一个问题，就是点击最后一个item，调用setcurrentItem 方法动画不能平滑过度到第一个item，非常跳跃

**Comment by zhpanvip** [comment]
因为使用的MAX_VALUE的方案，所以smooth滑动会出现这样的情况。

**Comment by interfans** [comment]
好的，谢谢啦，后续会随时关注更新的

**Comment by zhpanvip** [comment]
v3.1.2已发布，针对这个问题做了优化。

**Comment by interfans** [comment]
赞赞赞
