### ISSUE TITLE
一屏多页时addPageTransformer只能显示中间一页

### ISSUE THREAD

**Issue by GavinDon** [zhpanvip/BannerViewPager#123]
//viewPager2使用
        with(holder.getView<BannerViewPager<HotRecommendResp, BannerViewHolder>>(R.id.banner_view)) {
            setIndicatorVisibility(View.GONE)
            adapter = BannerAdpater()
            setAutoPlay(false)
            addPageTransformer(FlipHorizontalTransformer())
            setPageStyle(PageStyle.MULTI_PAGE_SCALE)
            setPageMargin(context.dip(10))
            setRevealWidth(context.dip(30))
            create(singleData)
        }

**Comment by zhpanvip** [comment]
请问使用的哪个版本？最新版本只需要设置revealWidth就可以了，具体你可以参考sample的代码。

**Comment by GavinDon** [comment]
> 请问使用的哪个版本？最新版本只需要设置revealWidth就可以了，具体你可以参考sample的代码。

设置的有啊 你看我的代码with(holder.getView<BannerViewPager<HotRecommendResp, BannerViewHolder>>(R.id.banner_view)) {
setIndicatorVisibility(View.GONE)
adapter = BannerAdpater()
setAutoPlay(false)
addPageTransformer(FlipHorizontalTransformer())
setPageStyle(PageStyle.MULTI_PAGE_SCALE)
setPageMargin(context.dip(10))
setRevealWidth(context.dip(30))
create(singleData)
}

**Comment by GavinDon** [comment]
码。

最新版本3.1.2&nbsp; 有setRevealWidth啊 你看我的代码with(holder.getView<BannerViewPager<HotRecommendResp, BannerViewHolder&gt;&gt;(R.id.banner_view)) {

setIndicatorVisibility(View.GONE)
adapter = BannerAdpater()
setAutoPlay(false)
addPageTransformer(FlipHorizontalTransformer())
setPageStyle(PageStyle.MULTI_PAGE_SCALE)
setPageMargin(context.dip(10))
setRevealWidth(context.dip(30))
create(singleData)
}

&nbsp;

你哈&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 瞪


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhpanvip"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 晚上8:32
收件人: "zhpanvip/BannerViewPager"<BannerViewPager@noreply.github.com&gt;; 
抄送: "登陆诺曼底（）-南"<530893850@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhpanvip/BannerViewPager] 一屏多页时addPageTransformer只能显示中间一页 (#123)





 
请问使用的哪个版本？最新版本只需要设置revealWidth就可以了，具体你可以参考sample的代码。

**Comment by zhpanvip** [comment]
你代码写的有问题吧，我在sample上验证了，通过setRevealWidth就可以实现。你把create方法放到with外边试试。

**Comment by GavinDon** [comment]
在setRevealWidth 同时设置了addPageTransformer就会出现只显示一页的情况。   如果不设置addPageTransformer 就ok的

**Comment by zhpanvip** [comment]
这应该是你Transformer的问题.你用库中默认的ScalePageTransformer跟OverlapPageTransformer都是可以的。

**Comment by GavinDon** [comment]
这两种效果和设置pageStyle是一样的？我想要其他的动画效果。这是transformer！ 能帮忙看下需要怎么改动。谢谢
`class FlipHorizontalTransformer : ViewPager2.PageTransformer {
    override fun transformPage(page: View, position: Float) {
        val rotation = 180f * position
        if (position > -0.5f && position < 0.5f) {
            page.visibility = View.VISIBLE
        } else {
            page.visibility = View.INVISIBLE
        }
        page.alpha = if (rotation > 90f || rotation < -90f) 0f else 1f
        page.pivotX = page.width * 0.5f
        page.pivotY = page.height * 0.5f
        page.rotationY = rotation
    }
}`
