### ISSUE TITLE
Viewpager2 嵌套bannerViewPager 滑动冲突问题

### ISSUE THREAD

**Issue by ss332** [zhpanvip/BannerViewPager#124]
当外层viewpager2是横向滑动的时候，banner的横向手动滑动被截取了，banner设置为竖向轮播就没有问题，我看了bannerViewPager的事件分发，ondepatch,oninterupt,是写好了滑动控制的，但是没有起作用，

**Comment by zhpanvip** [comment]
sample的首页就是VP2嵌套BannerViewPager没有出现滑动冲突的情况。你可以详细的描述下你的使用场景，方便分析问题。

**Comment by zhpanvip** [comment]
由其他布局引起的滑动冲突
