### ISSUE TITLE
Enable/Disable setUserInputEnabled on runtime

### ISSUE THREAD

**Issue by cacato86** [zhpanvip/BannerViewPager#127]
Hi! First of all congratulation on your nice work! 

Is it possible to enable Enable/Disable the user Input (scroll) when the adapter is already created? I want to enable or disable depending on some variables while the user advances.

Thanks!

**Comment by zhpanvip** [comment]
Hi!Will supported in next version.

**Comment by cacato86** [comment]
Also, is it possible to set the 'UserInput' for only one side, I mean, I want to enable the userInput only for the RIGHT movement.

Thanks for the support, nice job

**Comment by zhpanvip** [comment]
> Also, is it possible to set the 'UserInput' for only one side, I mean, I want to enable the userInput only for the RIGHT movement.
> 
> Thanks for the support, nice job

Sorry,I think this feature will not be supported in future version.Because this feature is
not a common feature for most developers.If necessary，you can download source code and supported by youslef.

**Comment by zhpanvip** [comment]
3.1.3 released
