### ISSUE TITLE
ROUND_RECT和gif不一致

### ISSUE THREAD

**Issue by LDJHXM** [zhpanvip/BannerViewPager#129]
ROUND_RECT设置并不是和示意图一样的圆角变矩形 而是都是矩形~最新版本

**Comment by zhpanvip** [comment]
指示器吗？可以贴下你图片跟代码看下

**Comment by LDJHXM** [comment]
![image](https://user-images.githubusercontent.com/23136744/83937410-e395d280-a7fe-11ea-8f31-1ab26cb425ad.png)
![image](https://user-images.githubusercontent.com/23136744/83937425-088a4580-a7ff-11ea-9828-4b51ba5357d7.png)
@zhpanvip

**Comment by zhpanvip** [comment]
图片比较模糊，不过看起来是圆角啊，你把高度设置的小一些就行了。有很多可自定义的选项，你参考Sample就可以实现示意图的样式了。
