### ISSUE TITLE
如何区分手动滚动和自动滚动呢~

### ISSUE THREAD

**Issue by LDJHXM** [zhpanvip/BannerViewPager#130]
如题

**Comment by zhpanvip** [comment]
抱歉，目前不支持区分是自动滚动还是手动滚动。

**Comment by LDJHXM** [comment]
嗯嗯~我们要求增加手动滚动的统计事件这就坑爹了~~多谢

**Comment by LDJHXM** [comment]
现在这样也可以在onPageScrollStateChanged通过state判断来区分  手动滚动的话会返回state=1 自动滚动则不会
