### ISSUE TITLE
长按时图片的scaleType会发生变化

### ISSUE THREAD

**Issue by jackma11** [zhpanvip/BannerViewPager#136]
使用3.1.3版本

手机型号为vivo V1818 

系统为8.1.0 

demo可以复现

图片设置scaleType为fitXY,在长按后发生变化

具体详见gif

![1245](https://user-images.githubusercontent.com/51396482/85241210-a28ff600-b46d-11ea-928f-9eaf908b424b.gif)

**Comment by jackma11** [comment]
测试了其他vivo和oppo,华为的机型,都没有这个问题
只有vivo funtouch OS9有这个问题😂😂😂

**Comment by zhpanvip** [comment]
是只有这个PageTransformer会出现还是所有情况都会有？

**Comment by jackma11** [comment]
刚刚试了一下,其他的PageTransformer也是一样的,但是只有WelcomeActivity才会有这个问题,里面的几个Fragment的都没有
