### ISSUE TITLE
RecyclerView中Banner被重建时页面滑动问题

### ISSUE THREAD

**Issue by zhpanvip** [zhpanvip/BannerViewPager#137]
BVP作为RecyclerView的Header时，如果在上拉加载时候调用了Banner的接口并对Banner进行了刷新，BVP会出现多个页面快速切换问题。
--------------------------------------------------------------------------------------------------------------------
解决方案有两种：
1.在上拉加载时不要调用Banner接口刷新Banner数据（一般Banner数据接口只需要在下拉刷新调用即可）
2.可以将refreshData改为create来解决。
推荐使用第一种方案。

**Comment by Maple201314** [comment]
同上，放到recyclerview的头部也会出现滑动问题

**Comment by zhpanvip** [comment]
> 同上，放到recyclerview的头部也会出现滑动问题

你直接使用的RecyclerView还是第三方库？sample的首页并没有出现类似情况。

**Comment by GoldDreams** [comment]
同上，ViewPager+Fragment组合，第一屏顶部放的banner,设置了自动滚动间隔，切换到其他Fragment,然后切换到第一屏会出现banner快速滚动的问题，几秒后才停下来 ,不切换到其他页面没发现类似问题。 VERSION=3.1.2

**Comment by zhpanvip** [comment]
> 同上，ViewPager+Fragment组合，第一屏顶部放的banner,设置了自动滚动间隔，切换到其他Fragment,然后切换到第一屏会出现banner快速滚动的问题，几秒后才停下来 ,不切换到其他页面没发现类似问题。 VERSION=3.1.2

这个bug是在交流群里提到的,但是我一直没有复现出来，不知道你们能否提供一个可以复现的demo?

**Comment by zhpanvip** [comment]
这个问题已经复现出来了，是由refreshData引起。大家可以暂时把refreshData改为create,来解决这个问题。我也会在后续版本中寻找解决方案对这个问题进行优化。

**Comment by guozhiqiang123** [comment]
BVP作为Recyclerview的header的时候，每次BVP轮播的时候，都会把Recyclerview滚动到顶部去，测试的手机是Android5的系统，高版本暂时没有出现这个问题。下面是gif演示：
![f2ca4f54a27da577f09a8175ee14630f](https://user-images.githubusercontent.com/20378988/93307832-0b4ffa00-f834-11ea-9981-4b62e7017c94.gif)

**Comment by zhpanvip** [comment]
> BVP作为Recyclerview的header的时候，每次BVP轮播的时候，都会把Recyclerview滚动到顶部去，测试的手机是Android5的系统，高版本暂时没有出现这个问题。下面是gif演示：
> ![f2ca4f54a27da577f09a8175ee14630f](https://user-images.githubusercontent.com/20378988/93307832-0b4ffa00-f834-11ea-9981-4b62e7017c94.gif)

可以在xml使用descendantFocusability属性控制。

**Comment by guozhiqiang123** [comment]
> > BVP作为Recyclerview的header的时候，每次BVP轮播的时候，都会把Recyclerview滚动到顶部去，测试的手机是Android5的系统，高版本暂时没有出现这个问题。下面是gif演示：
> > ![f2ca4f54a27da577f09a8175ee14630f](https://user-images.githubusercontent.com/20378988/93307832-0b4ffa00-f834-11ea-9981-4b62e7017c94.gif)
> 
> 可以在xml使用descendantFocusability属性控制。

可以解决问题，感谢！

**Comment by winlee28** [comment]
> 

descendantFocusability  设置什么值？ 我这边测试不行
