### ISSUE TITLE
打开来就闪退，看不懂什么问题

### ISSUE THREAD

**Issue by mutoujun** [zhpanvip/BannerViewPager#138]
![image](https://user-images.githubusercontent.com/32905492/85840587-50cdcf80-b7cf-11ea-9165-b7655b10a3ab.png)

**Comment by zhpanvip** [comment]
inflate布局文件时候报错了，这个应该不是库的问题，检查一下你项目环境看是什么问题引起的。

**Comment by mutoujun** [comment]
> inflate布局文件时候报错了，这个应该不是库的问题，检查一下你项目环境看是什么问题引起的。

我不知道怎么看，就是完全看不懂问题在哪里，我用的banner版本是最新的

**Comment by mutoujun** [comment]
> inflate布局文件时候报错了，这个应该不是库的问题，检查一下你项目环境看是什么问题引起的。

找到问题了，但是不知道怎么解决，问题是找不到viewpager2:Error inflating class androidx.viewpager2.widget.ViewPager2
即时我不用banner，我直接在布局里引用viewpager2一样是这个报错，可我不知道怎么解决，网上也找不到答案，能不能请教一下作者大哥，这个问题该怎么解决啊

**Comment by zhpanvip** [comment]
你是不是没有依赖ViewPager2？

**Comment by mutoujun** [comment]
> 你是不是没有依赖ViewPager2？

依赖了啊，但没有用，就是找不到，再说即使我不依赖viewpager2，banner框架里不也依赖了viewpager2吗，还是一样闪退啊，好奇怪啊

**Comment by mutoujun** [comment]
> 膨胀布局文件时候报错了，这个应该不是库的问题，检查一下你项目环境看是什么问题引起的。

我解决问题了，原来是我全局依赖的androidx.core的版本太低了，导致viewpager2里的androidx.core包下的一个文件找不到
