### ISSUE TITLE
使用疑惑

### ISSUE THREAD

**Issue by asjqkkkk** [zhpanvip/BannerViewPager#14]
作者你好，请问BannerViewPager是如何刷新的呢？我更新数据源后，调用了BannerViewPager中ViewPager的Adapter的notify..方法刷新，但是没有效果

**Comment by zhpanvip** [comment]
服务器返回数据后直接调用mBannerViewPager.create(response.getDataBeanList())即可，刷新也可以这样使用。可以参考demo中NetworkBannerActivity

**Comment by asjqkkkk** [comment]
就是使用create方法去代替notify...方法的意思吗😊

**Comment by asjqkkkk** [comment]
> 服务器返回数据后直接调用mBannerViewPager.create(response.getDataBeanList())即可，刷新也可以这样使用。可以参考demo中NetworkBannerActivity

好的，多谢
