### ISSUE TITLE
 关于开启与停止轮播的优化

### ISSUE THREAD

**Issue by ZQ173** [zhpanvip/BannerViewPager#140]
#20 
看介绍是这样说： “2.5.0之后版本无需自行在Activity或Fragment中管理stopLoop和startLoop方法，但这两个方法依旧保留对外开放  但是为了节省性能建议在onPause中停止轮播，在onResume中开启轮播”。

这方面可以参考另一个框架 https://github.com/youth5201314/banner，通过添加生命周期观察者 LifecycleObserver  ，新增 addBannerLifecycleObserver() 方法来绑定操作，进一步简化开发配置操作。

**Comment by zhpanvip** [comment]
很好的建议，会考虑在后续版本中加入。

**Comment by zhpanvip** [comment]
该issue已在3.1.4版本进行了优化，非常感谢您的建议。
