### ISSUE TITLE
模式为横向滑动时，不响应竖直方向的滑动事件？

### ISSUE THREAD

**Issue by dapanjimianpaigumian** [zhpanvip/BannerViewPager#142]

**Comment by zhpanvip** [comment]
你是在CoordinatorLayout+CollapsingToolbarLayout中使用的BVP吗？升级到最新版本试试看。

**Comment by jerry9433** [comment]
我用3.5.8版本，布局结构为CoordinatorLayout->AppBarLayout->CollapsingToolbarLayout->FrameLayout->LinearLayout->BannerViewPager
BannerViewPager为横向滑动，允许用户滑动，但是当手指按下的位置在BannerViewPager上时，垂直滑动事件被拦截，不会响应到外部的伸缩布局。

**Comment by zhpanvip** [comment]
> 我用3.5.8版本，布局结构为CoordinatorLayout->AppBarLayout->CollapsingToolbarLayout->FrameLayout->LinearLayout->BannerViewPager BannerViewPager为横向滑动，允许用户滑动，但是当手指按下的位置在BannerViewPager上时，垂直滑动事件被拦截，不会响应到外部的伸缩布局。

disallowParentInterceptDownEvent 调用这个方法试一下
