### ISSUE TITLE
多次调用mViewPagerBanner.refreshData会出现一屏三显setPageMargin失效

### ISSUE THREAD

**Issue by jiqianwen** [zhpanvip/BannerViewPager#143]
![QQ截图20200716125201](https://user-images.githubusercontent.com/26268908/87628400-6a758d80-c763-11ea-9d54-52b9197c5486.png)

**Comment by jiqianwen** [comment]
第一次调用refreshData正常，第二次调用refreshData左边间距失效，第三次调用refreshData右边间距失效，第四次调用refreshData恢复正常

**Comment by zhpanvip** [comment]
可以暂时使用create()替代refreshData。

**Comment by jiqianwen** [comment]
> 可以暂时使用create()替代refreshData。

使用create()暂时解决了，感谢

**Comment by zhpanvip** [comment]
这貌似是ViewPager2的bug，在ViewPager2中设置一屏多页，刷新数据后也会出现一样的问题。

**Comment by jiqianwen** [comment]
> 这貌似是ViewPager2的bug，在ViewPager2中设置一屏多页，刷新数据后也会出现一样的问题。

那只能暂时用create()替代了，希望后面官方会修复

**Comment by cowoboy007** [comment]
有办法做分页加载吗？
