### ISSUE TITLE
更新了代码 包没有更新 还是3.1.4

### ISSUE THREAD

**Issue by weikaiyun** [zhpanvip/BannerViewPager#144]
最新的设置代码是很有必要的 不然有些情况有问题

**Comment by zhpanvip** [comment]
是的，还没有发布。

**Comment by weikaiyun** [comment]
> 是的，还没有发布。

版主啥时候发布新包呀 项目等着上线 需要用到新包里的配置

**Comment by zhpanvip** [comment]
你是需要用disallowInterceptTouchEvent这个方法吗？现在可以发布一个版本。

**Comment by weikaiyun** [comment]
> 你是需要用disallowInterceptTouchEvent这个方法吗？现在可以发布一个版本。

是的
