### ISSUE TITLE
嵌套滑动冲突

### ISSUE THREAD

**Issue by weikaiyun** [zhpanvip/BannerViewPager#146]
CoordinatorLayout ->AppBarLayout + NestedScrollView ，其中NestedScrollView-> ViewPager -> recyclerView -> BannerViewPager 现在竖直滑动时 需要先滑动NestedScrollView 使CoordinatorLayout中APPBarLayout收起  然而现在会优先滑动 BannerViewPager 求问版主如何解决呀

**Comment by zhpanvip** [comment]
可以加交流群详细说明

**Comment by zhpanvip** [comment]
通过调用BVP的disallowInterceptTouchEvent(false)
