### ISSUE TITLE
是否支持rtl布局

### ISSUE THREAD

**Issue by linmomo** [zhpanvip/BannerViewPager#147]
感谢作者提供的库，因为项目需要支持RTL，所以自动滚动方向需要将从右往左滚动改为从左往右滚动，镜像翻转的布局，vp2原生已经支持，但是滚动方向需要改变，请问可以支持这个吗

**Comment by zhpanvip** [comment]
你好，暂时不支持RTL.

**Comment by linmomo** [comment]
好的，谢谢

**Comment by zhpanvip** [comment]
你可以通过getViewPager方法获取VP2然后设置RTL,但是指示器目前还不能支持。
