### ISSUE TITLE
onBindViewHolder

### ISSUE THREAD

**Issue by smileToWxm** [zhpanvip/BannerViewPager#150]
看了源码默认没有对onBindViewHolder的payloads方法进行处理，导致在notifyItemChanged(data,payloads)无效，
希望可以多添加个onBind附加payloads。
由于isCanLoop设为了private所以在调用BannerUtils.getRealPosition的时候需要通过反射去处理，希望能返回给外层

**Comment by zhpanvip** [comment]
1.不推荐直接通过Adapter去刷新数据，在循环模式下BVP内部对Item做了变换，notifyItemChanged(position)方法无法对应上真正的position，所以即使处理了payloads，刷新也可能是没有效果的。目前BVP仅支持通过BannerViewPager的refresh刷新数据。
2.关于isCanLoop private的问题主要是当时考虑canLoop本身就是开发者自己设置的，是否循环开发者本身是知道的，所以没有开放出来。

**Comment by smileToWxm** [comment]
> 1.不推荐直接通过Adapter去刷新数据，在循环模式下BVP内部对Item做了变换，notifyItemChanged(position)方法无法对应上真正的position，所以即使处理了payloads，刷新也可能是没有效果的。目前BVP仅支持通过BannerViewPager的refresh刷新数据。
> 2.关于isCanLoop private的问题主要是当时考虑canLoop本身就是开发者自己设置的，是否循环开发者本身是知道的，所以没有开放出来。

刚看了下refresh，内部是调用了notifyDataSetChanged，这是否会影响性能，关于循环模式下的payloads的position问题，不知是否可以采用同onBindViewHolder的BannerUtils.getRealPosition的方式去获取到真实的position去处理。
isCanLoop的问题，由于我这边大部分的轮播图适配器都是复用一个或者2个的所以需要通过外部传参的方式去得知isCanLoop的状态

**Comment by zhpanvip** [comment]
> > 1.不推荐直接通过Adapter去刷新数据，在循环模式下BVP内部对Item做了变换，notifyItemChanged(position)方法无法对应上真正的position，所以即使处理了payloads，刷新也可能是没有效果的。目前BVP仅支持通过BannerViewPager的refresh刷新数据。
> > 2.关于isCanLoop private的问题主要是当时考虑canLoop本身就是开发者自己设置的，是否循环开发者本身是知道的，所以没有开放出来。
> 
> 刚看了下refresh，内部是调用了notifyDataSetChanged，这是否会影响性能，关于循环模式下的payloads的position问题，不知是否可以采用同onBindViewHolder的BannerUtils.getRealPosition的方式去获取到真实的position去处理。
> isCanLoop的问题，由于我这边大部分的轮播图适配器都是复用一个或者2个的所以需要通过外部传参的方式去得知isCanLoop的状态

关于notifyDataSetChanged是否影响性能的问题我认为是可以忽略的，在数据量大的情况下notifyDataSetChanged对性能影响较大。但是，一般Banner的数据量不会很大，本着易用性的目的，没有对notifyXXX做太多处理。关于这一点后续如果有机会会考虑再做一些优化。
关于canLoop，这点都是开发者自己通过BannerViewPager的setCanLoop设置的，所以本身都应该知道是不是可以循环的。不过这个方法开放出来也是可以的。

**Comment by smileToWxm** [comment]
> > > 1.不推荐直接通过Adapter去刷新数据，在循环模式下BVP内部对Item做了变换，notifyItemChanged(position)方法无法对应上真正的position，所以即使处理了payloads，刷新也可能是没有效果的。目前BVP仅支持通过BannerViewPager的refresh刷新数据。
> > > 2.关于isCanLoop private的问题主要是当时考虑canLoop本身就是开发者自己设置的，是否循环开发者本身是知道的，所以没有开放出来。
> > 
> > 
> > 刚看了下refresh，内部是调用了notifyDataSetChanged，这是否会影响性能，关于循环模式下的payloads的position问题，不知是否可以采用同onBindViewHolder的BannerUtils.getRealPosition的方式去获取到真实的position去处理。
> > isCanLoop的问题，由于我这边大部分的轮播图适配器都是复用一个或者2个的所以需要通过外部传参的方式去得知isCanLoop的状态
> 
> 关于notifyDataSetChanged是否影响性能的问题我认为是可以忽略的，在数据量大的情况下notifyDataSetChanged对性能影响较大。但是，一般Banner的数据量不会很大，本着易用性的目的，没有对notifyXXX做太多处理。关于这一点后续如果有机会会考虑再做一些优化。
> 关于canLoop，这点都是开发者自己通过BannerViewPager的setCanLoop设置的，所以本身都应该知道是不是可以循环的。不过这个方法开放出来也是可以的。

好的，很感谢作者开源了这个库，很方便也简化了很多工作量。谢谢！
