### ISSUE TITLE
嵌套滚动问题，不响应点击事件

### ISSUE THREAD

**Issue by lkfxx** [zhpanvip/BannerViewPager#151]
BVP外层是NestedScrollView,viewpager2的item中有RecycleView，点击RecycleView不响应点击事件，点击RecycleView外面BVP会先滚动到顶部，然后才响应点击事件，大神帮忙看下！

**Comment by zhpanvip** [comment]
可以加讨论群详细说明问题

**Comment by xf222zt** [comment]
这个怎么解决了呢，我也遇到这个问题了。

**Comment by zhpanvip** [comment]
> 这个怎么解决了呢，我也遇到这个问题了。

这个不是BVP的问题，检查下你自己的代码。

**Comment by xf222zt** [comment]
我在外面有一层嵌套的ScrollView，我看到代码里有个disallowParentIntercep方法，但我已更新到3.4.0最新的版本，调不到这个。
