### ISSUE TITLE
Pad横屏状态下，点击item跳转新的界面，按返回，item会跳到下一个

### ISSUE THREAD

**Issue by li5972** [zhpanvip/BannerViewPager#152]
界面上只有一个BannerViewPager，使用MULTI_PAGE_SCALE模式，在pad横屏状态下，屏幕上可以看到5个，其中3个完全显示，两边的两个可以看到部分。滑动几个之后点击中间的item（最大的那个）跳转新的activity，然后点击返回按钮，回到BannerViewPager界面，item会跳到下一个（item的位置不变，只是中间那个大的变小，旁边的变大）

**Comment by zhpanvip** [comment]
注意设置布局文件的宽度为match,然后设置revealWidth可以控制左右两边显示出来的宽度。
第二个问题不要用refreshData(),改为create()方法可以解决。
如果依然有问题可以加交流群。

**Comment by li5972** [comment]
第二个问题如果用create的话，会有一个滑动的过程，需求是从新的activity返回后，BannerViewPager不要动，只改变item里的数据，如果用create，BannerViewPager会从第一个滑动到当前的item
