### ISSUE TITLE
是否能增加获取当前ItemView或者根据pos获取当前选择的View

### ISSUE THREAD

**Issue by ljackChen001** [zhpanvip/BannerViewPager#157]
是否能增加获取当前ItemView或者根据pos获取当前选择的View

**Comment by YuMengShuaii** [comment]
```
class ViewHolder(view: View) : BaseViewHolder<Model>(view) {
   
    override fun bindData(data: Model, position: Int, pageSize: Int) {
        itemView.tag = "$position"
    }
    
}

banner_view.registerOnPageChangeCallback(object : ViewPager2.OnPageChangeCallback() {
                override fun onPageScrolled(
                    position: Int,
                    positionOffset: Float,
                    positionOffsetPixels: Int
                ) {
     val itemView = banner_view.findViewById<ViewPager2>(R.id.vp_main).findViewWithTag<View>("$position")
}

```

**Comment by zhpanvip** [comment]
> ```
> class ViewHolder(view: View) : BaseViewHolder<Model>(view) {
>    
>     override fun bindData(data: Model, position: Int, pageSize: Int) {
>         itemView.tag = "$position"
>     }
>     
> }
> 
> banner_view.registerOnPageChangeCallback(object : ViewPager2.OnPageChangeCallback() {
>                 override fun onPageScrolled(
>                     position: Int,
>                     positionOffset: Float,
>                     positionOffsetPixels: Int
>                 ) {
>      val itemView = banner_view.findViewById<ViewPager2>(R.id.vp_main).findViewWithTag<View>("$position")
> }
> ```

这么写没问题吗？position是做了变换的，可能会出现多个itemView的tag是一样的情况的。

**Comment by lh1241698502** [comment]
能添加这个api来获取指定位置的view吗

**Comment by zhpanvip** [comment]
> 能添加这个api来获取指定位置的view吗

这个API应该不会支持。

**Comment by mikaelzero** [comment]
希望添加这个功能
