### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by FlodCoding** [zhpanvip/BannerViewPager#160]
个人觉得没必要在写个BaseBannerAdapter，直接使用RecyclerView.Adapter 即可。
理由如下：
- 完全没法使用databinding
- 假如banner里面的item仅仅是一个Imageview就没法直接在代码里new一个进去，而是必须写一个布局文件
- 并没有减少太多的代码量，反而是灵活性变差了

**Comment by zhpanvip** [comment]
关于BaseAdapter是必须要有的，因为BVP最核心的无限循环就是因为BaseAdapter才能运行的。另外，对于BVP内部对VP2做了很多处理，也是必须基于BaseAdapter的，这也导致无法直接使用RecycleView.Adapter。至于你说的没办法使用DataBinding，你可以参考[这里](https://github.com/zhpanvip/OneAndroid/blob/master/app/src/main/java/com/zhpan/oneandroid/base/DataBindingAdapter.java)

**Comment by FlodCoding** [comment]
ok
