### ISSUE TITLE
非AndroidX 版本

### ISSUE THREAD

**Issue by bingdu0** [zhpanvip/BannerViewPager#162]
有没有非AndroidX的版本，我这边对接的好多第三方的不支持AndroidX。

**Comment by zhpanvip** [comment]
非Androidx的只能使用2.x的版本了，[v2.x点这里](https://github.com/zhpanvip/BannerViewPager/tree/v_2.x)

**Comment by bingdu0** [comment]
@zhpanvip  2.x中的指示器我看着也是androidx的，，指示器有没有非androidx的

**Comment by zhpanvip** [comment]
你按着2.x的文档写就可以刻，2.x有support版本也有androidx版本，但用法是一样的。你要想看support版本的源码可以看jcenter分支下边。
