### ISSUE TITLE
Indicators below banner, is it possible?

### ISSUE THREAD

**Issue by ghostmane0404** [zhpanvip/BannerViewPager#165]
Good day, sir. Your implementation of banner is  wonderful and i really appreciate it. I wonder if there any possibilities to position indicator below banner, that would be great

**Comment by zhpanvip** [comment]
Hi! indicator below of banner is supported by setIndicator()，you can see the [sample](https://github.com/zhpanvip/BannerViewPager/blob/master/app/src/main/java/com/example/zhpan/circleviewpager/fragment/OthersFragment.java)
