### ISSUE TITLE
怎么能处理在onPageSelected的时候，更新可见和不可见的itemview

### ISSUE THREAD

**Issue by lh1241698502** [zhpanvip/BannerViewPager#166]
我们的轮播里面有图片和视频，想在选中的时候播放视频，没有选中的时候停止播放，图片上的有标签和动画，也想在选中和没有选中的时候处理UI

**Comment by zhpanvip** [comment]
你可以加交流群，群里有同学处理过类似问题。

**Comment by lh1241698502** [comment]
@zhpanvip 加群了，没有回复，能不能demo里加个例子

**Comment by Dboy233** [comment]
我公司也有类似的案子，不过我是用ViewPager2+fragment做的。用fragment的生命周期控制视频资源，通过拦截Touch事件实现。
