### ISSUE TITLE
Rxjava 3.x 什么时候支持适配

### ISSUE THREAD

**Issue by HymanYang** [zhpanvip/BannerViewPager#167]

**Comment by zhpanvip** [comment]
这个库并没有使用RxJava,需要适配什么？

**Comment by HymanYang** [comment]
com.github.zhpanvip.BannerViewPager:ideahttp下有依赖RxJava 2.x

**Comment by zhpanvip** [comment]
这个是一个轮播库，ideahttp这个仅仅是提供给app模块做网络请求的，跟BannerViewPager没有关系。如果你想使用ideahttp相关的代码你可以自行升级。

**Comment by HymanYang** [comment]
感谢，是我们引入错了依赖
