### ISSUE TITLE
CustomRecycleView 的点击事件ICustomRecycleViewOnClickListener 没效果

### ISSUE THREAD

**Issue by ToHappyBirth** [zhpanvip/BannerViewPager#169]
是不是应该在自建的Adapter 中重新开放ICustomRecycleViewOnClickListener接口？还是别的？

**Comment by zhpanvip** [comment]
点击事件直接通过BannerViewPager去设置。

**Comment by zhpanvip** [comment]
不建议在项目里边用demo中的CustomRecycleView，CustomRecycleView是从别处copy来的，没有在项目中使用过，BVP不会对CustomRecycleView进行维护。

**Comment by ToHappyBirth** [comment]
okay,thank you
