### ISSUE TITLE
indicator距离底部的margin应该可以调节比较好

### ISSUE THREAD

**Issue by 892848153** [zhpanvip/BannerViewPager#17]
indicator距离底部的margin应该可以调节比较好

**Comment by zhpanvip** [comment]
之前有考虑这个功能需求不是很大，所以没有添加API支持。如果有需要后续版本中会考虑添加响应API

**Comment by zhpanvip** [comment]
2.4.1添加新API setIndicatorMargin(int left, int top, int right, int bottom)
