### ISSUE TITLE
kotlin adapter Type mismatch.

### ISSUE THREAD

**Issue by benxin123** [zhpanvip/BannerViewPager#172]
把demo转成kotlin  mViewPagerHorizontal.setAdapter(HomeAdapter()) 会出现
Required:
BaseBannerAdapter<BannerData!, BaseViewHolder<BannerData>!>!
Found:
HomeAdapter

HomeAdapter已经继承了

**Comment by zhpanvip** [comment]
需要将BannerViewPager强转成BaseBannerAdapter<BannerData, BaseViewHolder<BannerData>>类型，或者声明成员变量BaseBannerAdapter<BannerData, BaseViewHolder<BannerData>>，然后通过findViewById获取BannerViewPager.详情请参考demo.
