### ISSUE TITLE
demo里快速滑动时不会切换下一个banner而是直接切换外面viewpager的fragment

### ISSUE THREAD

**Issue by fuguiniao** [zhpanvip/BannerViewPager#173]
下载的apk里快速滑动时不会切换下一个banner而是直接切换外面viewpager的fragment

**Comment by zhpanvip** [comment]
已经做了滑动冲突处理了，之所以会出现这样的情况大概率是因为在一屏多页的情况下滑动时触碰到了BVP的外部导致的。
