### ISSUE TITLE
说实话这个3.0版本的adapter使用太过繁琐了

### ISSUE THREAD

**Issue by Dboy233** [zhpanvip/BannerViewPager#177]
adapter不是用来数据填充的，转而交给了ViewHoler内部实现数据填充，adapter看上去好像就是代理了一下。
感觉adapter可以再简化一些操作，就像BaseRecyclerViewAdapterHelper这个库封装的一样。简化ViewHodler的操作。

**Comment by zhpanvip** [comment]
感谢建议，大概看了一下BRVH的Adapter，BRVH适用的场景比较复杂，内部根据功能分了多个BaseAdapter。而BVP的适用场景比较单一，没必要像BRVH一样维护多个BaseAdapter，对于简单的场景多个BaseAdapter反而让开发者使用起来更加不方便。另外，你提到的简化ViewHolder，其实你也完全可以不通过ViewHolder#bindData()方法去绑定数据，而是像BRVH一样在Adapter中通过ViewHolder.setXXX去设置数据（BVP的BaseViewHolder中的setXXX的相关方法后续版本可以改为public），通过这样的方式相比BRVH其实就是多写了一个ViewHolder,但省去了多个BaseAdapter。
当然，如果你有好的想法也欢迎PR。

**Comment by Dboy233** [comment]
我把这个adapter进行修改了，增加了两个class；
写了一个用例adapter；可以用ViewBinding DataBinding；当然以前的布局方式也保留了。
可否给我一个权限，我提交一下。你看看我这个方式是否可取，如果不行的话，你再还原代码。
![image](https://user-images.githubusercontent.com/37604230/101921366-e4714c00-3c07-11eb-827f-bf5a0d4461ee.png)
![image](https://user-images.githubusercontent.com/37604230/101921430-f4892b80-3c07-11eb-8d07-cb446e5e3cb8.png)
![image](https://user-images.githubusercontent.com/37604230/101921657-33b77c80-3c08-11eb-81e5-7e5afc2a3f9b.png)

**Comment by zhpanvip** [comment]
> 我把这个adapter进行修改了，增加了两个class；
> 写了一个用例adapter；可以用ViewBinding DataBinding；当然以前的布局方式也保留了。
> 可否给我一个权限，我提交一下。你看看我这个方式是否可取，如果不行的话，你再还原代码。
> ![image](https://user-images.githubusercontent.com/37604230/101921366-e4714c00-3c07-11eb-827f-bf5a0d4461ee.png)
> ![image](https://user-images.githubusercontent.com/37604230/101921430-f4892b80-3c07-11eb-8d07-cb446e5e3cb8.png)
> ![image](https://user-images.githubusercontent.com/37604230/101921657-33b77c80-3c08-11eb-81e5-7e5afc2a3f9b.png)

你需要fork一下这个项目，在你fork的仓库改，然后到我这个仓库提pull request.我这边review完了可以合到主分支。

**Comment by Dboy233** [comment]
OK
