### ISSUE TITLE
快速开始文档是否需要更新？

### ISSUE THREAD

**Issue by ALuoBo** [zhpanvip/BannerViewPager#180]
尝试跟着快速开始使用。进行到Step4 ，提示缺少ViewHolder 。
---------------------
自己定义一个继承BaseViewHolder 之后就晕了，bindData（） 怎么使用？找不着头绪。
---------------------
是否有Demo code 仓库？

**Comment by zhpanvip** [comment]
最新版本已经不需要ViewHolder了，按着文档写就行了。demo请下载源码。

**Comment by ALuoBo** [comment]
@zhpanvip TKS，AS自动提示的最新版本为3.2.0 ， 经您的提示，以手动更新到3.4.0.问题解决
