### ISSUE TITLE
Not good view in fragment

### ISSUE THREAD

**Issue by MeysamSMH7** [zhpanvip/BannerViewPager#187]
hi,
im useing this library and a very good library i ever used
but this a very simple problem!
In activity its working very good but in fragment it dosnt show other slides 
you know whats im saying?
![image](https://user-images.githubusercontent.com/42836468/107877023-007ebb80-6edf-11eb-8a3e-47481e60da6a.png)
users cant see pink and blue sliders its happen just in fragments
i hope you can fix this problem

**Comment by zhpanvip** [comment]
Did you used RTL mode?

**Comment by MeysamSMH7** [comment]
yes, Im useing it

**Comment by MeysamSMH7** [comment]
i just put BannerView to LinearLayout that layoutDirection is ltr
problem solved
