### ISSUE TITLE
展示一张轮播图的时候建议不拦截滑动事件，交由父View处理

### ISSUE THREAD

**Issue by AnJiuZhe** [zhpanvip/BannerViewPager#190]
使用BannerViewPager嵌套在viewpager中，只有一张图的时候，viewpager滑动事件被消费了

**Comment by zhpanvip** [comment]
内部一张图片时候并没有拦截事件，可否给出详细的使用案例？或者加交流群说明情况。

**Comment by AnJiuZhe** [comment]
新版本已修复
