### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by JeremyLam1** [zhpanvip/BannerViewPager#192]
為什麼用2.X的android support版本， implementation 'com.zhpan.library:bannerview:2.7.5'，項目還是會提示androidx信息？

**Comment by zhpanvip** [comment]
这个依赖链接是jecenter上的版本，是android support的。可以检查下你的依赖是不是有问题，或者降一个版本用2.7.4试试看。

建议尽快迁移到androidx,jcenter在5月份之后也要关闭了，届时2.x的jcenter版本可能会收到影响。
