### ISSUE TITLE
为什么从网络得到数据或再refreshData会卡屏幕

### ISSUE THREAD

**Issue by jackpanz** [zhpanvip/BannerViewPager#193]
layout_emergency.setVisibility(View.VISIBLE);
banner_emergency_info.refreshData(emergencyInfos);
去掉refreshData就不卡屏幕

**Comment by jackpanz** [comment]
我的页面上有多个banner,都是从网络得到数据，卡的很厉害

**Comment by zhpanvip** [comment]
把refreshData改成create呢？

**Comment by jackpanz** [comment]
public void setupEmergencyInfo() {

        banner_emergency_info
                .setAutoPlay(true)
                .setOrientation(ViewPager2.ORIENTATION_VERTICAL)
                .setScrollDuration(2000)
                .setInterval(6000)
                .setIndicatorVisibility(View.GONE)
                .setLifecycleRegistry(getLifecycle())
                .setAdapter(new MainEmergencyAdapter(v -> {
                    startEmergencyInfoActivity(v.getTag());
                }))
                .create();

        Api.getEmergencyInfo(new SimpleCallback<List<EmergencyInfo>>(this) {
            public void onSuccess(int index, List<EmergencyInfo> emergencyInfos) {
                if (CollectionUtils.isNotEmpty(emergencyInfos)) {
                    layout_emergency.setVisibility(View.VISIBLE);

                    banner_emergency_info.refreshData(emergencyInfos);
                }
            }
        });

    }

**Comment by jackpanz** [comment]
Api.getEmergencyInfo(new SimpleCallback<List<EmergencyInfo>>(this) {
            public void onSuccess(int index, List<EmergencyInfo> emergencyInfos) {
                if (CollectionUtils.isNotEmpty(emergencyInfos)) {
                    layout_emergency.setVisibility(View.VISIBLE);

//                    banner_emergency_info.refreshData(emergencyInfos);

                    banner_emergency_info
                            .setAutoPlay(true)
                            .setOrientation(ViewPager2.ORIENTATION_VERTICAL)
                            .setScrollDuration(2000)
                            .setInterval(6000)
                            .setIndicatorVisibility(View.GONE)
                            .setLifecycleRegistry(getLifecycle())
                            .setAdapter(new MainEmergencyAdapter(v -> {
                                startEmergencyInfoActivity(v.getTag());
                            }))
                            .create();

                }
            }
        });
我这样写不卡屏，但是不出数据。

**Comment by jackpanz** [comment]
横的就不会有卡，竖的就出现卡UI

**Comment by zhpanvip** [comment]
create方法一样可以传一个List集合

**Comment by jackpanz** [comment]
反馈一下，感觉一个页面用太多会出现卡顿的问题，可能我的页面本身内容比较多吧。
用一个就不会，现在我只用一个，其他我自己实现一下吧。

**Comment by zhpanvip** [comment]
检查下是不是你使用的方式有问题，demo的Home页有三个Banner运行也是正常的，没有卡顿的情况。详细的反馈可以添加交流群。

**Comment by zhpanvip** [comment]
检测了一下BannerViewPager刷新时的帧率，总体上还是非常稳定的，不存在掉帧问题，所以可以检查下你的代码是否有问题。
