### ISSUE TITLE
3.5.0版本如何去掉滑动到边缘的阴影效果？

### ISSUE THREAD

**Issue by zaaach** [zhpanvip/BannerViewPager#194]

**Comment by zhpanvip** [comment]
这是系统效果，可以自己搜下。



发送自我的盖乐世



-------- 原始信息 --------
发件人： Zaaach ***@***.***>
日期: 2021/4/7 17:29 (GMT+08:00)
收件人： zhpanvip/BannerViewPager ***@***.***>
抄送： Subscribed ***@***.***>
主题： [zhpanvip/BannerViewPager] 3.5.0版本如何去掉滑动到边缘的阴影效果？ (#194)


―

**Comment by zaaach** [comment]
嗯，暂时用反射去掉了=。=
