### ISSUE TITLE
可以支持图片和视频混合轮播吗

### ISSUE THREAD

**Issue by yangqb** [zhpanvip/BannerViewPager#195]
可以支持图片和视频混合轮播吗

**Comment by zhpanvip** [comment]
支持的



发送自我的盖乐世



-------- 原始信息 --------
发件人： yangqb ***@***.***>
日期: 2021/4/21 15:16 (GMT+08:00)
收件人： zhpanvip/BannerViewPager ***@***.***>
抄送： Subscribed ***@***.***>
主题： [zhpanvip/BannerViewPager] 可以支持图片和视频混合轮播吗 (#195)


可以支持图片和视频混合轮播吗

―

**Comment by yangqb** [comment]
好的，谢谢，我试试
