### ISSUE TITLE
Handler内存泄漏

### ISSUE THREAD

**Issue by leaps339** [zhpanvip/BannerViewPager#196]
![image](https://user-images.githubusercontent.com/37408750/115649815-9bba6400-a35a-11eb-860f-529ef5d9dc76.png)
![image](https://user-images.githubusercontent.com/37408750/115649903-c60c2180-a35a-11eb-9ae9-a56ca1b2336e.png)
它看起来发生了内存泄漏，可以使用自定义Handler解决它么

**Comment by leaps339** [comment]
我已经在View的onDetachedFromWindow中调用stopLoop，甚至在调用之前通过反射使isLooping变量为true，可内存泄漏依然在发生

**Comment by zhpanvip** [comment]
setLifecycleRegistry方法调用了吗

**Comment by leaps339** [comment]
> setLifecycleRegistry方法调用了吗

没有😳，我将调用，再观察下

**Comment by leaps339** [comment]
> setLifecycleRegistry方法调用了吗

内部只有addObserver，而没有removeObserver么。需要业务方手动调用吗
