### ISSUE TITLE
垂直得 ViewPage2 得fragment中嵌套WebView 滑动冲突 

### ISSUE THREAD

**Issue by open9527** [zhpanvip/BannerViewPager#197]
垂直得 ViewPage2 得fragment中嵌套WebView   WebView 无法滑动

**Comment by zhpanvip** [comment]
可以尝试调用disallowParentInterceptDownEvent这个方法看是否有用，如果没用的话就需要你自己处理滑动冲突了。

**Comment by zhpanvip** [comment]
有用到BVP吗？你这是VP2的滑动冲突吧？

**Comment by open9527** [comment]
不是 BVP得  ,用    private boolean mClampedY;

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        if (event.getAction() == MotionEvent.ACTION_DOWN) {
            super.requestDisallowInterceptTouchEvent(!mClampedY);
        }
        return super.onTouchEvent(event);
    }

    @Override
    protected void onOverScrolled(int scrollX, int scrollY, boolean clampedX, boolean clampedY) {
        LogUtils.i(TAG, "onOverScrolled: " + clampedY);
        mClampedY = clampedY;
        if (!clampedY) {
            super.requestDisallowInterceptTouchEvent(true);
        }
        super.onOverScrolled(scrollX, scrollY, clampedX, clampedY);
    }

可以处理了,谢谢
