### ISSUE TITLE
startLoop, stopLoop，可以隐藏起来吧。你自己监听生命周期去做。

### ISSUE THREAD

**Issue by 892848153** [zhpanvip/BannerViewPager#20]

**Comment by zhpanvip** [comment]
View不能监听到Activity的生命周期的，View只能感知onAttachedToWindow和onDetachedFromWindow,这两个方法跟Activity声明周期不一致。所以startLoop和stoopLoop还是要留给开发者自己来管理。

**Comment by zhpanvip** [comment]
放到onAttachedToWindow和onDetachedFromWindow里边管理其实也未尝不可。
