### ISSUE TITLE
setIndicatorSlideMode为IndicatorSlideMode.SCALE时不显示checked的颜色

### ISSUE THREAD

**Issue by Samler-Lee** [zhpanvip/BannerViewPager#206]
setIndicatorSlideMode为IndicatorSlideMode.SCALE时不显示checked的颜色：
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/26178720/121547740-fc068180-ca3e-11eb-9908-ddfcffd774d7.png">
![07AA7606B4F55CCE7145DA0F1676B5F7](https://user-images.githubusercontent.com/26178720/121547867-1b9daa00-ca3f-11eb-80f2-231a7364750a.jpg)

**Comment by zhpanvip** [comment]
setSliderWidth方法有两个参数需要设置，需要设置成不一样长才行，这可能是一个bug。

**Comment by Samler-Lee** [comment]
> setSliderWidth方法有两个参数，SCALE模式下选中和未选中时需要设置成不一样长才行。

感谢解答
