### ISSUE TITLE
setPageStyle(MULTI_PAGE_SCALE) and  setRoundRect(radius) not working

### ISSUE THREAD

**Issue by SushilJangra** [zhpanvip/BannerViewPager#208]
Please update your library.

Some functions are not working like :

- setPageStyle(MULTI_PAGE_SCALE)
- setRoundRect(radius)

**Comment by zhpanvip** [comment]
These methods are working in sample apk.please check your code and refer to the sample code to check what is wrong.



发送自我的盖乐世



-------- 原始信息 --------
发件人： SushilJangra ***@***.***>
日期: 2021/6/19 19:44 (GMT+08:00)
收件人： zhpanvip/BannerViewPager ***@***.***>
抄送： Subscribed ***@***.***>
主题： [zhpanvip/BannerViewPager] setPageStyle(MULTI_PAGE_SCALE) and setRoundRect(radius) not working (#208)


Please update your library.

Some functions are not working like :

  *   setPageStyle(MULTI_PAGE_SCALE)
  *   setRoundRect(radius)

―

**Comment by SushilJangra** [comment]
Can you help me with this code? What I am doing wrong?

bannerViewPager
                .setScrollDuration(800)
                .setOffScreenPageLimit(2)
                .setLifecycleRegistry(getLifecycle())
                .setIndicatorStyle(IndicatorStyle.CIRCLE)
                .setIndicatorSlideMode(IndicatorSlideMode.WORM)
                .setInterval(4000)
                .setIndicatorGravity(IndicatorGravity.END)
                .setIndicatorSliderRadius(getResources().getDimensionPixelSize(R.dimen.dp_3))
                .disallowParentInterceptDownEvent(true)
                .setIndicatorView(binding.viewpager.indicatorView)
                .setIndicatorSliderColor(getActivity().getResources().getColor(R.color.grayMid),
                        getActivity().getResources().getColor(R.color.theme_medium))
                .setAdapter(bannerAdapter)
                .setPageMargin(getResources().getDimensionPixelOffset(R.dimen.dp_15))
                .setRevealWidth(getResources().getDimensionPixelOffset(R.dimen.dp_15))
                .setPageStyle(PageStyle.MULTI_PAGE_SCALE)
                .setAutoPlay(true)
                .setRoundCorner(20)
                .create();

**Comment by zhpanvip** [comment]
delete the line "setIndicatorView(binding.viewpager.indicatorView)"
