### ISSUE TITLE
BannerAdapter怎么复用布局

### ISSUE THREAD

**Issue by qq570026938** [zhpanvip/BannerViewPager#213]
好像无法复用布局，导致我有个布局报错child already has a parent. You must call removeView() on the child's parent；请问除了我在我的布局中remove之外，这个库本身是否支持复用布局呢

**Comment by zhpanvip** [comment]
不但BVP不支持，整个Android也不支持一个View有多个parent。

**Comment by qq570026938** [comment]
> 不但BVP不支持，整个Android也不支持一个View有多个parent。

嗯嗯，明白，我意思是adapter中的布局是不是没有复用，比如一个图片这次显示了，下次滑动到这个图片之后，图片的布局imageview不是之前那个了

**Comment by qq570026938** [comment]
> 不但BVP不支持，整个Android也不支持一个View有多个parent。

嗯嗯，明白，我意思是adapter中的布局是不是没有复用，比如一个图片这次显示了，下次滑动到这个图片之后，图片的布局imageview不是之前那个了，我打印的imageview的hashcode 经常变动

**Comment by zhpanvip** [comment]
缓存基于RecyclerView,了解一下RecyclerView的缓存机制。

**Comment by qq570026938** [comment]
我可能说的不清楚，我意思是你的这个banneradapter是不是没实现布局的复用，我用的是你的BnnerAdapter做的，里面打印的通一个位置的布局的hashcode经常变动，说明是销毁重建的，不是复用的之前的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhpanvip/BannerViewPager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月26日(星期一) 上午9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhpanvip/BannerViewPager] BannerAdapter怎么复用布局 (#213)





 
缓存基于RecyclerView,了解一下RecyclerView的缓存机制。

**Comment by zhpanvip** [comment]
你用的哪个版本？如果用的是2.x的版本是基于ViewPager的，ViewPager本身支持offscreenPage设置，自己去做复用本身就是一件很傻的事情。如果是3.x版本，缓存是基于RecyclerView的，也无需理会缓存复用问题。

**Comment by qq570026938** [comment]
我用的是最新的这个版本，你可以试试，打印一下布局的hashcode，我用的databinding绑定的布局，布局里面有个FrameLayout会变动


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhpanvip/BannerViewPager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月26日(星期一) 上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhpanvip/BannerViewPager] BannerAdapter怎么复用布局 (#213)





 
你用的哪个版本？如果用的是2.x的版本是基于ViewPager的，ViewPager本身支持offscreenPage设置，自己去做复用本身就是一件很傻的事情。如果是3.x版本，缓存是基于RecyclerView的，也无需理会缓存复用问题。

**Comment by zhpanvip** [comment]
> 我用的是最新的这个版本，你可以试试，打印一下布局的hashcode，我用的databinding绑定的布局，布局里面有个FrameLayout会变动
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhpanvip/BannerViewPager" ***@***.***&gt;; 发送时间:&nbsp;2021年7月26日(星期一) 上午10:05 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zhpanvip/BannerViewPager] BannerAdapter怎么复用布局 (#213) 你用的哪个版本？如果用的是2.x的版本是基于ViewPager的，ViewPager本身支持offscreenPage设置，自己去做复用本身就是一件很傻的事情。如果是3.x版本，缓存是基于RecyclerView的，也无需理会缓存复用问题。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没有问题的，了解一下RecyclerView的缓存机制吧。
