### ISSUE TITLE
设置SCALE 和ROUND_RECT的时候没效果且选中状态颜色不显示

### ISSUE THREAD

**Issue by sceneren** [zhpanvip/BannerViewPager#217]
![image](https://user-images.githubusercontent.com/6612998/129835270-5ab6067d-3350-4a53-b116-b89801727974.png)

![image](https://user-images.githubusercontent.com/6612998/129835173-44499145-c4b9-47c9-b80d-e3ce7dd3ff02.png)

设置SCALE 和ROUND_RECT的时候没效果且选中状态颜色不显示

**Comment by sceneren** [comment]
而且Kotlin 强转对感觉不太友好

**Comment by zhpanvip** [comment]
请参考sample，SCALE模式下需要设置slider宽度。因为BVP是泛型类，BVP的声明建议使用findViewById.

**Comment by sceneren** [comment]
建议可以在xml里面配置indicator宽度和高度，而且BannerViewPager的代码可以优化的，根本不需要给范型

**Comment by zhpanvip** [comment]
有想法可以提PR
