### ISSUE TITLE
How to change size of indicator

### ISSUE THREAD

**Issue by HuuNguyen312** [zhpanvip/BannerViewPager#228]
Dear @zhpanvip 

Currently, I can't change size of indicator.
Please add attribute "bvp_indicator_size"

Thanks

**Comment by zhpanvip** [comment]
Do you want to set the radius or width of the indicator slider ? You can try to use "bvp_indicator_radius"

**Comment by HuuNguyen312** [comment]
Work like a charm
Thank you
