### ISSUE TITLE
你好，我刷新界面  指示器圆点会莫名其妙消失

### ISSUE THREAD

**Issue by chenni521** [zhpanvip/BannerViewPager#229]
homeBannerAdapter = new HomeBannerAdapter();
        homeBannerAdapter.setContext(getActivity());
        homeBannerView.setLifecycleRegistry(getLifecycle())
                .setAdapter(homeBannerAdapter)
                .create();

 homeBannerView.refreshData(homeDeviceInfosBean.getDeviceInfos());

 <com.zhpan.bannerview.BannerViewPager
                android:id="@+id/home_banner_view"
                android:layout_width="match_parent"
                android:layout_height="@dimen/dp_390"
                app:bvp_auto_play="false"
                app:bvp_can_loop="false"
                app:layout_constraintTop_toTopOf="parent" />

https://share.weiyun.com/5iEzTlnr   视频链接

**Comment by zhpanvip** [comment]
能否提供一个可以复现的demo，方便排查问题
