### ISSUE TITLE
 BaseBannerAdapter<Int>()出现Type mismatch.

### ISSUE THREAD

**Issue by LGlxb** [zhpanvip/BannerViewPager#237]
使用Demo部分界面可行 demo转换成kt 
开发中提示转换错误
猜测是泛型问题 Any的Int实现 应该是不安全的
开发环境和demo略有不同 不知是哪里问题

**Comment by zhpanvip** [comment]
检查下代码

**Comment by LGlxb** [comment]
> 检查下代码

需要将BannerViewPager强转成BaseBannerAdapter<BannerData, BaseViewHolder>类型，或者声明成员变量BaseBannerAdapter<BannerData, BaseViewHolder>，然后通过findViewById获取BannerViewPager.详情请参考demo.

**Comment by LGlxb** [comment]
> 检查下代码

看到了去年的的lssues
