### ISSUE TITLE
在DialogFragment中使用  图片滑动出现锯齿

### ISSUE THREAD

**Issue by huanghongfu** [zhpanvip/BannerViewPager#255]

**Comment by zhpanvip** [comment]
有图片可以贴一下

**Comment by huanghongfu** [comment]
https://user-images.githubusercontent.com/23544687/163078801-5f8f5444-d026-4cca-b563-fabfae20a327.mp4

这是视频

**Comment by zhpanvip** [comment]
> 

哪里有锯齿？Banner里边的图片有锯齿吗？如果是图片有锯齿不应该是Banner的问题。
