### ISSUE TITLE
放到RecyclerView.Adapter 里面  在列表划入划出  banner会轮播快速滚动好几下

### ISSUE THREAD

**Issue by z876335662** [zhpanvip/BannerViewPager#257]

**Comment by zhpanvip** [comment]
哪个版本？这个问题最新版本已经修复了

**Comment by z876335662** [comment]
3.5.3

**Comment by zhpanvip** [comment]
升级到最新版本3.5.5

**Comment by z876335662** [comment]
升级最新还是会出现

**Comment by wkbin** [comment]
新版本并没有修复

**Comment by JamesGZM** [comment]
> 升级最新还是会出现

3.5.7这个问题还存在 
我在onViewAttachedToWindow加入了onResume
在onViewDetachedFromWindow加入了onPause

**Comment by zhpanvip** [comment]
> > 升级最新还是会出现
> 
> 3.5.7这个问题还存在 我在onViewAttachedToWindow加入了onResume 在onViewDetachedFromWindow加入了onPause

可以录个屏我看下什么表现，应该跟这个bug不是同一个问题

**Comment by yxiangTang** [comment]
3.5.11这个bug还存在
