### ISSUE TITLE
宽度适配存在bug

### ISSUE THREAD

**Issue by Hynsn** [zhpanvip/BannerViewPager#261]
使用dp值，指定两侧宽度会出现展示数目不一样的情况。
建议试一下其他两个函数是不是能解决这种适配问题。屏幕参数如下
屏幕宽度 - 转换后dp2px值 - 像素密度
1080  420 3.0
1080  367 2.625
getDimensionPixelSize getDimensionPixelOffset

**Comment by zhpanvip** [comment]
需要你自己做屏幕适配

**Comment by Hynsn** [comment]
> 需要你自己做屏幕适配
不是吧 内部计算都在控件里
