### ISSUE TITLE
版本由3.5.4升级为3.5.6或者3.5.5都会报错找不到类

### ISSUE THREAD

**Issue by lsy-onin** [zhpanvip/BannerViewPager#269]
版本由3.5.4升级为3.5.6或者3.5.5都会报错找不到类

Class referenced in the layout file, com.zhpan.bannerview.BannerViewPager, was not found in the project or the libraries

**Comment by lsy-onin** [comment]
我现在只能用3.5.4，升级后就不行了

**Comment by zhpanvip** [comment]
是不是你配置有问题？3.5.5版本已经发布大半年了，没有人反馈过找不到类的问题。看下依赖是不是没拉到？

**Comment by lsy-onin** [comment]
我现在3.5.5能拉到，3.5.6还是拉不到
两个月前，在我的Mac上能拉到3.5.5，win10上拉不到3.5.5

**Comment by zhpanvip** [comment]
应该不是库的问题，是你那边环境问题。

**Comment by lsy-onin** [comment]
https://stackoverflow.com/questions/50389211/android-studio-maven-url-https-jitpack-io-cant-download
将  maven { url "https://jitpack.io" } 改为   maven { url "https://www.jitpack.io" } 并且移动至第一
