### ISSUE TITLE
赞

### ISSUE THREAD

**Issue by zxqSmile** [zhpanvip/BannerViewPager#27]
代码简洁，看着很舒服，棒棒哒

**Comment by zhpanvip** [comment]
感谢支持，后续还会对代码结构进行优化

**Comment by zxqSmile** [comment]
轮播图，能设置一下滑动模式吗，我不太想响应用户的滑动的事件。让控件按时间自己切换。

**Comment by zhpanvip** [comment]
不太理解你的意思

**Comment by zxqSmile** [comment]
左滑右滑的时候，不是会切换上一页和下一页吗，我的意思是对于滑动不响应。或者说，设置个开关，让控件是否响应滑动事件。

**Comment by zhpanvip** [comment]
这个功能感觉需求不是很大，你们项目需要这个功能吗？不过会考虑在下个版本添加api支持。刚刚2.4.3分支已经commit了这个功能-disableTouchScroll.
