### ISSUE TITLE
在设置setScrollDuration()后持续插入数据addData()，无滚动动画效果。

### ISSUE THREAD

**Issue by KunPengZheng** [zhpanvip/BannerViewPager#274]
addData()的内部使用了resetCurrentItem(getCurrentItem())导致。有什么办法可以插入数据但是不破坏滚动效果

**Comment by zhpanvip** [comment]
有配置混淆吗？能否详细描述或者贴个图？

**Comment by NGC185air110** [comment]
val banner =
            (itemHolder.v<BannerViewPager<BannerModel>>(R.id.banner_operating) as BannerViewPager<BannerModel>).apply {
                setLifecycleRegistry(lifecycle)
                setInterval(4000)
                setScrollDuration(1000)
                setIndicatorSliderColor(
                    ContextCompat.getColor(context, R.color.color_4DA3A3A3),
                    ContextCompat.getColor(context, R.color.color_4D000000)
                )
                setIndicatorStyle(IndicatorStyle.ROUND_RECT)
                setIndicatorSliderRadius(SizeUtils.dp2px(6F))
                setIndicatorSliderGap(SizeUtils.dp2px(5F))
                setIndicatorSliderWidth(SizeUtils.dp2px(6F), SizeUtils.dp2px(10F))
                adapter = viewBindingSampleAdapter
            }
        banner.create()

```
 banner.addData(bannerData)
banner.startLoop()
```
上面是我的配置  我是在addData之后使用了startLoop就有了滚动效果
版本号:com.github.zhpanvip:BannerViewPager:3.5.4

**Comment by zhpanvip** [comment]
这样不应该使用addData，换成refreshData就可以了
