### ISSUE TITLE
指示器，设置宽高、间隔 方法无效

### ISSUE THREAD

**Issue by wystyle1** [zhpanvip/BannerViewPager#276]
IndicatorOptions options = new IndicatorOptions();
            options.setCheckedSliderColor(0xFF8C8C8C);
            options.setNormalSliderColor(0xFFD8D8D8);
            options.setIndicatorStyle(IndicatorStyle.ROUND_RECT);
            options.setSlideMode(IndicatorSlideMode.SMOOTH);
            options.setShowIndicatorOneItem(false);
            options.setCheckedSliderWidth(VZPixelUtil.dp2px(getActivity(), 20));
            options.setNormalSliderWidth(VZPixelUtil.dp2px(getActivity(), 20));
            options.setSliderHeight(VZPixelUtil.dp2px(getActivity(), 40));
            options.setSliderGap(VZPixelUtil.dp2px(getActivity(), 50));
            IndicatorView indicatorView = helper.getView(R.id.banner_indicator);
            indicatorView.setIndicatorOptions(options);

**Comment by zhpanvip** [comment]
需要通过BannerViewPager暴露的接口设置这些参数

**Comment by wystyle1** [comment]
> BannerViewPager

解决了，给你点赞！！！
