### ISSUE TITLE
setCurrentItem(int item,boolean smoothScroll)方法无法让指示器切换

### ISSUE THREAD

**Issue by Code-Yu-1998** [zhpanvip/BannerViewPager#277]
当setCurrentItem(int item,boolean smoothScroll)中的smoothScroll为false，当data的size为2时，调用后，指示器就不会发生变化，还是原来的位置

**Comment by zhpanvip** [comment]
你是不是代码写的有问题，我这里测试是正常的。

**Comment by Code-Yu-1998** [comment]
我测试了，发现加上setRevealWidth()创建时候就会出现这种情况

**Comment by Code-Yu-1998** [comment]
触发条件：当前data的数量为2时且setRevealWidth()或在Layout中设置了revealWidth，调用setCurrentItem(index,false)后，其指示器不会发送变化，作者可以看看什么问题导致的
