### ISSUE TITLE
建议，增加一个参数，控制轮播切换时候，是否需要需要动画

### ISSUE THREAD

**Issue by wystyle1** [zhpanvip/BannerViewPager#280]
private boolean smoothScroll = true;
 private void handlePosition() {
    if (mBannerPagerAdapter != null && mBannerPagerAdapter.getListSize() > 1 && isAutoPlay()) {
      mViewPager.setCurrentItem(mViewPager.getCurrentItem() + 1,smoothScroll);
      mHandler.postDelayed(mRunnable, getInterval());
    }
  }

**Comment by wystyle1** [comment]
有些场景就是不要左右或者上下滚动动画，静默切换，不打扰用户

**Comment by zhpanvip** [comment]
3.5.7 新增一个API setAutoPlaySmoothly
