### ISSUE TITLE
BannerViewPager 添加或者移除item，会出现异常

### ISSUE THREAD

**Issue by juwuguo1988** [zhpanvip/BannerViewPager#281]
BannerViewPager 调用insertItem 或者removeItem 时，展示内容会出现抖动，由于 mBannerPagerAdapter.notifyDataSetChanged()是刷新整个列表，所以导致选中的item显示异常，insertItem 和removeItem的方法里notifyDataSetChanged改成 notifyItemChanged(index)即可

**Comment by zhpanvip** [comment]
能否补充一下具体什么异常

**Comment by zhpanvip** [comment]
> BannerViewPager 调用insertItem 或者removeItem 时，展示内容会出现抖动，由于 mBannerPagerAdapter.notifyDataSetChanged()是刷新整个列表，所以导致选中的item显示异常，insertItem 和removeItem的方法里notifyDataSetChanged改成 notifyItemChanged(index)即可

因为内部index进行了转换，担心notifyItemChanged(index)可能会导致问题。

**Comment by zhpanvip** [comment]
demo中添加与移除item并没有出现抖动问题，这个issue先关掉了，有问题后续再提

**Comment by longxuewei** [comment]
这个问题我也遇到过导致App崩溃错误信息就是晚上讨论的很多的那个状态错误的问题日志如下：

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionBaseViewHolder
