### ISSUE TITLE
create 方法内部自动循环bug

### ISSUE THREAD

**Issue by wystyle1** [zhpanvip/BannerViewPager#284]
在Activity/fragment的初始化oncreate方法中，调用 bannerViewPager设置自动轮播，并调用create(list)方法初始化，

因某些原因，导致activiy/fragment未到onresume 状态（比如viewpager 预加载场景） ，

但是create 方法中直接调用startLoop，没有判断生命周期状态

应该需要在调用startLoop前，判断Lifecycle 是onresume状态时，才可以自动开始轮播！！！

**Comment by zhpanvip** [comment]
很好的问题，下个版本会优化
