### ISSUE TITLE
横屏使用掉帧厉害，竖屏则完全没有问题

### ISSUE THREAD

**Issue by yhz199132** [zhpanvip/BannerViewPager#286]
使用代码
`bannerViewPager.setScrollDuration(600)
                    .setOffScreenPageLimit(2)
                    .setLifecycleRegistry(getLifecycle())
                    .setInterval(5000)
                    .setIndicatorVisibility(View.GONE)
                    .disallowParentInterceptDownEvent(true)
                    .setIndicatorSliderColor(getColor(R.color.colorAccent),
                            getColor(R.color.colorPrimary))
                    .setAdapter(imageBannerAdapter)
                    .create();
   viewModel.getImageListData().observe(this, list -> {
                bannerViewPager.refreshData(list);
    });`
设备竖屏完全正常，使用横屏则掉帧厉害，logcat显示在主线程做了太多工作
使用版本com.github.zhpanvip:bannerviewpager:3.5.7

**Comment by zhpanvip** [comment]
检查一下是不是你APP其他地方在主线程做耗时操作了，我这里测试不管横屏竖屏基本都能达到最大帧率
