### ISSUE TITLE
mViewPager.setLifecycleRegistry(fragment.lifecycle) 是否必须注册

### ISSUE THREAD

**Issue by Badwritten** [zhpanvip/BannerViewPager#288]
场景：在fragment里面第一次有banner数据，设置了这个lifecycle，第二次刷新页面没有banner了，因为注册了这个lifecycle，导致注册轮播回调（registerOnPageChangeCallback）一直触发，想问问如果解决这个问题；

**Comment by zhpanvip** [comment]
> ```
> public BannerViewPager<T, VH> setLifecycleRegistry(Lifecycle lifecycleRegistry) {
>     lifecycleRegistry.addObserver(this);
>     return this;
> }
> ```
> 
> 是否可以提供一个类似我截图这个remove方法 谢谢！ ![image](https://user-images.githubusercontent.com/29095116/198995932-57a03880-e218-4492-9db2-573b16cd49d6.png)

不是一定要调用setLifecycleRegistry ，如果不使用这个方法可以在onDestory的时候手动调用BVP的stopLoop方法。或者在onResume、onStop分别调用 startLoop和stopLoop。

后续版本会添加removeObserver API
