### ISSUE TITLE
BannerViewPager.refreshData()时ANR

### ISSUE THREAD

**Issue by Jasperben** [zhpanvip/BannerViewPager#289]
Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 12.  Wait queue head age: 5598.7ms.)

**Comment by zhpanvip** [comment]
根据已有信息并不能判断是否是BVP导致，是否可以给出更详细的信息
