### ISSUE TITLE
可不可以添加带进度条的样式

### ISSUE THREAD

**Issue by bingdu0** [zhpanvip/BannerViewPager#29]
感谢作者的开源 希望作者能维护下去
希望添加 进度条的样式 的指示器，每个指示器的点形状 变成进度条 ，进度条满了之后切换下一张

**Comment by zhpanvip** [comment]
这个你可以根据自己需求进行绘制，参考ReadMe的自定义IndicatorView。

**Comment by zhpanvip** [comment]
指示器样式太多，源码中不可能内置所有的样式，而且如果内置太多样式就需要为某个样式单独添加API接口，会使得大量代码冗余。所以留出了接口给开发者自己根据需求来绘制。
