### ISSUE TITLE
从别的页面返回到展示Banner的页面时，不会自动恢复轮播

### ISSUE THREAD

**Issue by jerry9433** [zhpanvip/BannerViewPager#295]
v3.5.8

1、BannerOptions.java 中设置stopLoopWhenDetachedFromWindow默认为true
2、但在BannerViewPager.java 第1091行，监听生命周期onResume时，判断为false时执行startLoop
3、导致在设置autoPlay = true,canLoop = true时，切换页面再返回时，banner不会再自动轮播
4、请去除此处的!
```java
 @OnLifecycleEvent(Lifecycle.Event.ON_RESUME)
  public void onResume() {
    if (!isStopLoopWhenDetachedFromWindow()) {
      startLoop();
    }
  }
```

**Comment by zhpanvip** [comment]
可以暂时先用低版本
