### ISSUE TITLE
节日轮播动画是否支持（如何自定义addPageTransformer）

### ISSUE THREAD

**Issue by Badwritten** [zhpanvip/BannerViewPager#296]
![image](https://user-images.githubusercontent.com/29095116/210515920-c43248d1-6399-4c79-9848-e748f73a17fd.png)
SVID_20230103_102446_1.mp4

**Comment by Badwritten** [comment]
大佬麻烦指点一二

**Comment by zhpanvip** [comment]
目前不支持这样的效果
