### ISSUE TITLE
是否可以增加手动切换方法

### ISSUE THREAD

**Issue by wkbin** [zhpanvip/BannerViewPager#297]
开发中遇到需要左右加两个箭头，通过点击左右箭头切换上一个或下一个
目前我的做法是 点击左滑 banner.setCurrentItem(banner.current - 1,true) 点击右滑 banner.setCurrentItem(banner.current+ 1,true)，
现在的问题是 向左没问题，向右点击按钮向右到最后一个item，点击按钮就没反应了，
是否可以暴露相关切换方法？

**Comment by zhpanvip** [comment]
新版本问题已经修复，可以参考最新代码的Demo
