### ISSUE TITLE
当传入datalist的size=2的时候，使用setCurrentItem滑动方向会出现异常

### ISSUE THREAD

**Issue by SunShineOrangeJuice** [zhpanvip/BannerViewPager#298]
if (item == 0 && realPosition == pageSize - 1) {
          mViewPager.setCurrentItem(currentItem + 1, smoothScroll);
        } else if (realPosition == 0 && item == pageSize - 1) { //size=2只会走这个判断
          mViewPager.setCurrentItem(currentItem - 1, smoothScroll);
        } else {
          mViewPager.setCurrentItem(currentItem + (item - realPosition), smoothScroll);
        }
具体表现为setCurrentItem(1)时，banner会从0的左边划入，正常的情况需要从右边划入

**Comment by zhpanvip** [comment]
这个bug跟 #252 应该是同一个问题，可以跟踪 #252 ，这里先关掉了，

**Comment by zhpanvip** [comment]
你这里使用场景是不是需要点击某个Item的时候自动滚动到这个Item来呢？如果是这样的场景，我可以加一个setOnPageClickListener(OnPageClickListener onPageClickListener,
      boolean scrollToThisItem)，第二个参数传个true进来就可以了。

setCurrentItem的这种方案目前是解决不了这个问题的

**Comment by zhpanvip** [comment]
问题已修复，使用方式可以参考最新代码的Demo

**Comment by SunShineOrangeJuice** [comment]
版本更新至3.5.10后问题已解决，感谢~！
