### ISSUE TITLE
BaseBannerAdapter

### ISSUE THREAD

**Issue by CrowForKotlin** [zhpanvip/BannerViewPager#300]
使用ViewBinding和DataBinding的话为什么不自定义一个ViewHolder，使用作者的BaseViewHolder那可以在OnCreateViewHolder内初始化bingding给ViewHolder，接下来在onBindViewHolder中直接holder.binding.xxx就可以了，毕竟在onBind中去重新加载一次次的布局性能消耗也不小.

**Comment by zhpanvip** [comment]
示例代码仅供参考，你可以使用自定义的ViewHolder来实现

**Comment by zhpanvip** [comment]
文档已更新
