### ISSUE TITLE
not an issue but i need help

### ISSUE THREAD

**Issue by gitadam0** [zhpanvip/BannerViewPager#307]
hello Im a beginer and i would love if somebody could give me a simple example like this beacause i couldnt understand much of the whole app and thank you 

![image_2023-04-13_124116625](https://user-images.githubusercontent.com/93042738/231761417-cb38c093-c2bd-47d8-a924-9036efbef231.png)

**Comment by zhpanvip** [comment]
The easiest way is to read this document : https://github.com/zhpanvip/BannerViewPager/wiki/01.Quick-Starts
