### ISSUE TITLE
垂直RecyclerView 嵌套 BannerViewPager ，BannerViewPager 左右滑动滑不动

### ISSUE THREAD

**Issue by wystyle1** [zhpanvip/BannerViewPager#309]
垂直recyclerView 其中一个item是 bannerViewPager,
bannerViewPager 左右滑动划几下，就滑不动了，是否有滑动冲突了？？？

**Comment by wystyle1** [comment]
bannerViewPager.setIndicatorView(helper.getView(R.id.banner_indicator));
bannerViewPager.setIndicatorSliderGap(VZPixelUtil.dp2px(getActivity(), 4));
bannerViewPager.setIndicatorHeight(VZPixelUtil.dp2px(getActivity(), 2));
bannerViewPager.setIndicatorSliderWidth(VZPixelUtil.dp2px(getActivity(), 8));
bannerViewPager.setAutoPlaySmoothly(false);
bannerViewPager.setAdapter();

**Comment by zhpanvip** [comment]
参考一下Demo代码，另外排查一下是否是由混淆导致的问题？
