### ISSUE TITLE
如果数据过多,指示器显示的会有些问题

### ISSUE THREAD

**Issue by LeonShannon** [zhpanvip/BannerViewPager#312]
我的数据大约有40个,然后指示器就会超出屏幕,不能聚焦
<img width="439" alt="image" src="https://github.com/zhpanvip/BannerViewPager/assets/24221796/6b2923ac-967e-4cd7-a855-f0c8953ebb45">

**Comment by zhpanvip** [comment]
目前未考虑指示器过多的情况，可以使用自定义指示器
