### ISSUE TITLE
垂直指示器位置

### ISSUE THREAD

**Issue by weinierfei** [zhpanvip/BannerViewPager#313]
`.setOrientation(ViewPager2.ORIENTATION_VERTICAL)
.setIndicatorStyle(IndicatorStyle.CIRCLE)
.setIndicatorGravity(IndicatorGravity.END)
.setIndicatorSlideMode(IndicatorSlideMode.NORMAL)`
这么设置，指示器位于右下角，不能垂直居中；

`.setIndicatorGravity(IndicatorGravity.CENTER)`
这么设置的话，指示器在页面的正中间。

如果要右侧垂直居中，咋设置？

**Comment by zhpanvip** [comment]
参考这里 https://github.com/zhpanvip/BannerViewPager/blob/master/app/src/main/res/layout/fragment_others.xml
