### ISSUE TITLE
禁止循环之后，有办法让最后一张图贴边滑动不了吗？

### ISSUE THREAD

**Issue by haoYeaph** [zhpanvip/BannerViewPager#323]
![Screenshot_20231008-114918](https://github.com/zhpanvip/BannerViewPager/assets/109566278/b718bbad-0a75-4aea-8085-170e316212f9)
弄成像这样向右滑不了
![Screenshot_20231008-114959](https://github.com/zhpanvip/BannerViewPager/assets/109566278/bcb3e34d-23ef-499c-95ae-7e038a3857cb)

**Comment by zhpanvip** [comment]
这个目前支持不了
