### ISSUE TITLE
控件顶部有大概1px的白色横条

### ISSUE THREAD

**Issue by wxcican** [zhpanvip/BannerViewPager#38]
使用的是com.zhpan.library:bannerview:2.3.5。

**Comment by zhpanvip** [comment]
建议先尝试下最新版本2.4.3.1,我稍后会核实一下最新版本是否也有该问题。另外2.5.0也会在最近两天发布。感谢支持！

**Comment by wxcican** [comment]
最新版本2.4.3.1也是有这个问题哦。

**Comment by zhpanvip** [comment]
方便留下你的联系方式吗？我这边试了没有相关问题呀，你也可以先检查以下布局文件或者图片顶部是否有留白。

**Comment by wxcican** [comment]
找到问题了，UI给的图少给了2像素，坑爹啊。感谢你的回复~
