### ISSUE TITLE
请问怎么刷新某单个pager啊，比如刷新自定义布局，第三个pager上的textview的内容，其他界面不变？

### ISSUE THREAD

**Issue by jahenryhan** [zhpanvip/BannerViewPager#47]

**Comment by zhpanvip** [comment]
目前BannerViewPager没有刷新功能，如果数据改变可以调用create(List<T> list)方法。

**Comment by jahenryhan** [comment]
好的，想问下大神，滑到下个界面，只需要下个界面显示一半怎么写呀？（ initIndicatorView 方法怎么写？）
//定义两个变量，这个两个变量是表示滑动时候，positionOffset 是从大到
  //小的变化，还是从小到大的变化。用于在滑动时候，避免多次调用一个方法
  private boolean isSmallToBig = true;
  private boolean isBigToSmall = false;

   //记录上一次滑动的positionOffsetPixels值
   private int lastValue = -1;
   @Override
    public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
        if (positionOffset != 0) {
            mCurrentPage = position;
            boolean isLeft = true;
            if (lastValue >= positionOffsetPixels) {
                //右滑
                isLeft = false;
            } else if (lastValue < positionOffsetPixels) {
                //左滑
                isLeft = true;
            }
            setIndiactorView(positionOffset,isLeft);
        }
        lastValue = positionOffsetPixels;

    }

    private void setIndiactorView(float positionOffset,boolean isLeft) {
       
       //设定滑动的边界，这里设置的滑动到一半
        float radiusOffsetHead = 0.5f;
        //如果滑动小于一半，通过isSmallToBig这个变量来避免多次调用
       // initIndicatorView 方法
        if (positionOffset <= radiusOffsetHead && !isSmallToBig) {

            initIndicatorView(mCurrentPage);
            isSmallToBig = true;
            isBigToSmall = false;

        } else if (positionOffset > radiusOffsetHead && !isBigToSmall) {
          //超过一半。如果是左滑，就-1，如果是右滑，就+1
            int currnt  = isLeft ? mCurrentPage + 1 : mCurrentPage - 1;
            initIndicatorView(currnt);
            isBigToSmall = true;
            isSmallToBig = false;
        }
    }
