### ISSUE TITLE
你好，滑动监听会回调两次，当再调用mViewPager.create()更新数据后就会回调两次，请问怎么解决呀？

### ISSUE THREAD

**Issue by jahenryhan** [zhpanvip/BannerViewPager#48]
mViewPager.setOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int i, float v, int i1) {

            }

            @Override
            public void onPageSelected(int i) {
                KLog.e(i);
                //这里会回调两次
            }

            @Override
            public void onPageScrollStateChanged(int i) {

            }
        });

**Comment by zhpanvip** [comment]
是最新版本吗

**Comment by jahenryhan** [comment]
非安卓X 2.5.0版本,请问最新版是多少啊？

**Comment by zhpanvip** [comment]
Readme 底部有QQ群，可以加下群讨论。

**Comment by zhpanvip** [comment]
这个问题会在2.5.2版本修复

**Comment by Erichkko** [comment]
+1

**Comment by zhpanvip** [comment]
2.5.2已修复，Androidx 2.5.2刚刚已经发布，Android support 2.5.2版本发布会稍晚些。
