### ISSUE TITLE
itemView包含带海拔的view，滑动的时候会闪一下

### ISSUE THREAD

**Issue by strivecheng** [zhpanvip/BannerViewPager#50]
大佬你好，用了你的banner，非常不错。但是我的itemView配合cardView使用的，因为带海拔，滑动切换的时候都会闪一下，我试了demo里面，也是这样的，帮忙看一下，谢谢。

**Comment by zhpanvip** [comment]
可以贴一下你item布局吗

**Comment by strivecheng** [comment]
> 可以贴一下你item布局吗

就一个cardview，我加qq群了，大佬同意 一下

**Comment by timmy-gzw** [comment]
我也是一样的,xml布局包含cardview的时候,会闪一下

**Comment by strivecheng** [comment]
> 我也是一样的,xml布局包含cardview的时候,会闪一下

对的，我也是cardview

**Comment by zhpanvip** [comment]
你们用cardview是要添加阴影吗？如果只是添加阴影可以先到https://inloop.github.io/shadow4android/这个网站生成一个带阴影的.9图替代。这个问题我还要再看一下。

**Comment by strivecheng** [comment]
> 你们用cardview是要添加阴影吗？如果只是添加阴影可以先到https://inloop.github.io/shadow4android/
> 这个网站生成一个带阴影的.9图替代。这个问题我还要再看一下。

对就加了个阴影，就是海拔

**Comment by zhpanvip** [comment]
添加阴影建议使用https://inloop.github.io/shadow4android/
这个网站生成带阴影的.9图替代CardView。

**Comment by zhpanvip** [comment]
Fixed in v3.0.0
