### ISSUE TITLE
自动轮播&循环

### ISSUE THREAD

**Issue by FuYiJin** [zhpanvip/BannerViewPager#51]
像是引导页这种需求

希望兼容这种模式，自动轮播和不循环

现在代码都设置死了，开启其中一项另一项也强制开启了

**Comment by zhpanvip** [comment]
引导页自动轮播但不能循环？这样不很奇怪么

**Comment by LDJHXM** [comment]
好像是有这方面的需求 我现在就有一个是轮播到最后一页就停止了  就是类似淘宝的滑动到最后一张图片后再次右滑可以进行其他操作 例如跳转
   @@@![image](https://user-images.githubusercontent.com/23136744/88998489-c1af5c80-d324-11ea-9b24-abef93168272.png)
@zhpanvip
