### ISSUE TITLE
在ViewPager2下使用时无法滑动Banner

### ISSUE THREAD

**Issue by yuzhiqiang1993** [zhpanvip/BannerViewPager#55]
在ViewPage2中的Fragment使用Banner时，滑动Banner时实际上触发的是ViewPager2的滑动效果，请问大佬有么有好的解决办法或者在demo中写个这样的示例，谢谢。

**Comment by yuzhiqiang1993** [comment]
在BannerViewPager中处理下事件分发后可以了，添加了以下代码

`    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        int action = ev.getAction();
        switch (action) {
            case MotionEvent.ACTION_DOWN:

                getParent().requestDisallowInterceptTouchEvent(true);
                break;
            case MotionEvent.ACTION_MOVE:

                break;
            case MotionEvent.ACTION_UP:
            case MotionEvent.ACTION_CANCEL:
                getParent().requestDisallowInterceptTouchEvent(false);

            default:
                break;
        }

        return super.dispatchTouchEvent(ev);
    }
`
暂时没有发现会引起其他问题，希望能帮到作者以及其他人员

**Comment by zhpanvip** [comment]
非常感谢你的代码。另外你这么处理在不能循环的情况下可能会有些问题，滑动到最后一个可能会使ViewPage2无法滑动。等我试下没问题的话会在下个版本优化一下，或者你也可以直接提PR过来合到2.5.3分支。

**Comment by zhpanvip** [comment]
这个问题其实是ViewPager2的一个bug,ViewPager2正式版已经发布了，不知道以后版本会不会修复这个问题。

**Comment by yuzhiqiang1993** [comment]
我用的应该就是最新的正式版，1.0.0版本。不过目前没有什么问题了

**Comment by zhpanvip** [comment]
Fix in v2..7.2
