### ISSUE TITLE
Round_rect 不支持吗？

### ISSUE THREAD

**Issue by wangrui460** [zhpanvip/BannerViewPager#58]
指示器不支持 Round_rect 吗？

**Comment by zhpanvip** [comment]
支持的，请升级版本到2.5.2.通过setIndicatorStyle 
(ROUND_RECT)设置圆角矩形指示器

**Comment by zhpanvip** [comment]
这貌似是一个bug, 注解忘了添加ROUND_RECT了。等下个版本可以修复。

**Comment by zhpanvip** [comment]
2.5.2版本可以通过布局文件app:bvp_indicator_style来设置圆角矩形
<com.zhpan.bannerview.BannerViewPager
        android:id="@+id/banner_view"
        android:layout_width="match_parent"
        app:bvp_indicator_style="round_rect"
        android:layout_height="200dp" />
