### ISSUE TITLE
banner 设为自动轮播，setPageTransformerStyle 后有bug，表现为：banner 自动滚动一段时间后，position 返回不正确

### ISSUE THREAD

**Issue by ZQ173** [zhpanvip/BannerViewPager#60]
如题， list 容器数量是 3，点击 banner 打印出 log 来，发现 position 分别是：0、2、2。
不设置 setPageTransformerStyle  这个属性的话，position 就正常。

**Comment by zhpanvip** [comment]
你好，请问你是在demo中出现的还是在项目中出现的，我在demo中测试了半个小时，各种PageStyleTransfomerStyle都尝试了并没有出现position错乱的情况。是否可以提供详细的复现流程以便排查和修复相关问题？或者你也可以扫描README末尾附带QQ群二维码加群详细交流。期待回复。

**Comment by ZQ173** [comment]
周六大晚上的，那么晚还在维护此项目，辛苦了。我设置的动画如下：
setPageTransformerStyle(TransformerStyle.DEPTH)
下午再测试了一遍，发现还和 setPageMargin 参数有关系。
在开启动画的时候，要记得 setPageMargin，不然点击出来的 position 就不对。
使用 demo 中的 HomeFragment 页面，把 setPageMargin(BannerUtils.dp2px(10)) 注释掉后，position 就是 0、1、3、3 了。

**Comment by zhpanvip** [comment]
按着你的步骤注释掉setPageMargin(BannerUtils.dp2px(10))，打印的position跟点击的position依然是正确的呀

**Comment by zhpanvip** [comment]
Fix in v2.6.0
