### ISSUE TITLE
偶尔白屏

### ISSUE THREAD

**Issue by hexu2016** [zhpanvip/BannerViewPager#61]
好像基于ViewPager的都会偶尔白屏,怎么解决呢

**Comment by zhpanvip** [comment]
能详细描述下使用情况吗？我用了这么久没见过白屏的情况呀。

**Comment by hexu2016** [comment]
> 能详细描述下使用情况吗？我用了这么久没见过白屏的情况呀。

就是作为recyclerView的一个viewType使用的，好像还没开始滚动切换到别的页面再回来更容易复现

**Comment by zhpanvip** [comment]
你好，可以加下README末尾的QQ群详细交流嘛？因为我这实在是没有复现出来空白页的情况。demo的第一个页面的Banner就是在RecyclerView中的一个viewType，但是貌似从来没有见到过空白页出现哎。

**Comment by luxunchina** [comment]
我也出现了偶尔白屏的情况，使用Kotlin编写，加载的是资源图片，不定时出现同一个图片的白屏，但是出现白屏后，下一次轮播又不会出现了，比较鬼畜，能不能看到全凭运气。可能几个小时会出现个一两次。设备是常亮设备，做广告的，所以一般我能注意到白屏的情况。之前的版本是2.6.4，现在给升级到2.6.6试试能不能解决

**Comment by zhpanvip** [comment]
> 我也出现了偶尔白屏的情况，使用Kotlin编写，加载的是资源图片，不定时出现同一个图片的白屏，但是出现白屏后，下一次轮播又不会出现了，比较鬼畜，能不能看到全凭运气。可能几个小时会出现个一两次。设备是常亮设备，做广告的，所以一般我能注意到白屏的情况。之前的版本是2.6.4，现在给升级到2.6.6试试能不能解决

这个bug的作者白屏的原因是因为自身ViewPager嵌套Fragment不规范引起的BannerViewPager白屏。你可以先检查下自身代码是否有问题，也欢迎加群交流。
