### ISSUE TITLE
加载不了网络图片

### ISSUE THREAD

**Issue by dyshero** [zhpanvip/BannerViewPager#71]
网络图片加载不出来

**Comment by zhpanvip** [comment]
不要使用demo的图片加载，请使用自己的图片加载框架加载图片。



来自 魅族 PRO 6 Plus



-------- 原始邮件 --------
发件人：dyshero <notifications@github.com>
时间：2019年12月20日 19:20
收件人：zhpanvip/BannerViewPager <BannerViewPager@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：[zhpanvip/BannerViewPager] 加载不了网络图片 (#71)


网络图片加载不出来
