### ISSUE TITLE
itemView延时或不出现，page之间间距不对

### ISSUE THREAD

**Issue by zwb1992** [zhpanvip/BannerViewPager#72]
我用的是2.4.3.1版本，触发条件：一次手动触摸快速滑动两个itemView的时候（一次滑动两个），新出的itemView会延迟或者不出现，且距离当前itemView的距离变大

**Comment by zhpanvip** [comment]
请先使用2.6.1尝试，2.4.3.1后边版本已经优化了很多。如果有问题可以加群交流。

**Comment by zwb1992** [comment]
我的项目还没有用androidX，2.6.1支持非androidX的吗？

**Comment by zhpanvip** [comment]
现在已经支持了，你可以升级试下看。

**Comment by zwb1992** [comment]
用了2.6.1，发现一样的问题

**Comment by zhpanvip** [comment]
你描述的我没太明白什么问题 ReadMe文档 底部有群二维码，可以加qq 群交流。

**Comment by zhpanvip** [comment]
setPageOffscreenLimt(3)可以解决该问题
