### ISSUE TITLE
我正常使用 在fragment 中切换 之后 直接ANR

### ISSUE THREAD

**Issue by ousq** [zhpanvip/BannerViewPager#73]
如题

**Comment by zhpanvip** [comment]
能详细描述下使用场景吗，或者你可以对比一下demo有哪些地方不同。是不是某些潜在原因引起的。还有你用的哪个版本？

**Comment by zhpanvip** [comment]
紧急发布了一个2.6.3版本，你可以尝试下2.6.3是否还有ANR问题。

**Comment by ousq** [comment]
sorry  忘记看了  我就是正常在fragment 是要 模拟器使用 四个fragment 先切换到 最后一个在点回来就ANR

**Comment by ousq** [comment]
我使用2.6.2的版本 和demo 差不多的 现在就是切换很卡  
![image](https://user-images.githubusercontent.com/18591884/71537935-21dcbb00-295e-11ea-9964-016bd054e212.png)
![image](https://user-images.githubusercontent.com/18591884/71537940-2b662300-295e-11ea-85d3-9872768179a6.png)
![image](https://user-images.githubusercontent.com/18591884/71537941-315c0400-295e-11ea-8cab-46365b461c6f.png)
应该是这样的步骤吧

**Comment by ousq** [comment]
使用 最新版 2.6.2 没有发现卡顿现象

**Comment by zhpanvip** [comment]
好的，感谢支持。2.6.4版本还会真对这个问题优化，彻底解决卡顿问题。可以关注最近版本发布情况。
