### ISSUE TITLE
在ViewPage+Fragment中使用

### ISSUE THREAD

**Issue by guozhiqiang123** [zhpanvip/BannerViewPager#74]
在ViewPage下面的每一个Fragment中都有banner，并且Fragment是复用的，当快速翻页滑动，不一会儿就ANR了。
下面是相关信息
![QQ截图20191226154007](https://user-images.githubusercontent.com/20378988/71464921-11a9cc00-27f6-11ea-9391-8c995194793f.png)

**Comment by zhpanvip** [comment]
这个问题应该跟无限轮播时候设置了MAX_INTGER有关系，等下个版本修复再试试看。

**Comment by zhpanvip** [comment]
紧急发布了一个2.6.3版本，你可以尝试下2.6.3是否还有ANR问题。

**Comment by zhpanvip** [comment]
2.6.3已修复ANR，2.6.4优化ANR
