### ISSUE TITLE
正在向ViewPager2迁移么

### ISSUE THREAD

**Issue by Dboy233** [zhpanvip/BannerViewPager#78]
正在向ViewPager2迁移么

**Comment by zhpanvip** [comment]
目前还未开始迁移ViewPager2

**Comment by wotoutengleha** [comment]
什么时候会迁移呢

**Comment by zhpanvip** [comment]
现在还没着手迁移，即使迁移了也要一段时间调试才能发布，估计还需要一些时间。按说现在不影响使用的，有什么必须要迁移的条件么？

**Comment by wotoutengleha** [comment]
没有 就是想用新的控件 等ViewPager2发布稳定版的时候可以迁移吗

**Comment by zhpanvip** [comment]
稳定版已经发布了，迁移已经在考虑了，不过VP2还存在嵌套滑动冲突问题，虽然可以通过代码自己解决冲突，但是还是存在一些问题。迁移后API变化也可能会比较大。

**Comment by wotoutengleha** [comment]
感谢开源  本库非常棒

**Comment by zhpanvip** [comment]
多谢支持
