### ISSUE TITLE
圆角问题

### ISSUE THREAD

**Issue by zhukai78** [zhpanvip/BannerViewPager#80]
设置PageStyle.MULTI_PAGE_OVERLAP跟setPageMargin方式后，中间图是圆角，左右背面两张图无法展现圆角。。

有啥解决方法吗？谢谢

**Comment by zhpanvip** [comment]
可以贴下代码么

**Comment by zhukai78** [comment]
1、 
(banner_view as BannerViewPager<Any, ImageResourceViewHolder>)
                            .setIndicatorMargin(0, 0, 0, BannerUtils.dp2px(10f))
                            .setIndicatorGravity(IndicatorGravity.CENTER)
            .setAutoPlay(true)
            .setPageMargin(88)
//            .setRoundCorner(24)
            .setPageStyle(PageStyle.MULTI_PAGE_OVERLAP)
//            .setIndicatorStyle(IndicatorStyle.ROUND_RECT)
//            .setIndicatorRadius(32)
            .setInterval(5000)
            .setIndicatorSlideMode(IndicatorSlideMode.SMOOTH)
            .setHolderCreator{(  ImageResourceViewHolder(24))}
            .setCanLoop(true)
            .create(imgs)


2、
class ImageResourceViewHolder(private val roundCorner: Any?) : ViewHolder<Any?> {
    private val roundedCorners =  RoundedCorners(roundCorner as Int)

    private val options = RequestOptions.bitmapTransform(roundedCorners)
    override fun getLayoutId(): Int {
        return R.layout.item_banner_page
    }
    override fun onBind(itemView: View, data: Any?, position: Int, size: Int) {
        val imageView = itemView.findViewById<CornerImageView>(R.id.banner_image)
        imageView.scaleType=ImageView.ScaleType.FIT_XY
//        imageView.setImageResource(data!! as Int)
        // 通过RequestOptions扩展功能
        // 加载图片
        GlideApp.with(JtRobotApplication.instance)
            .load(data)
            .diskCacheStrategy(DiskCacheStrategy.ALL)
            .dontAnimate()
            .apply(options)
            .into(imageView)
        imageView.setRoundCorner(roundCorner as Int)

            }

}

**Comment by zhpanvip** [comment]
没有问题呀？Overlap状态下左右两边被上边覆盖了一部分，本来就不会显示圆角的。

**Comment by zhukai78** [comment]
确实是因为覆盖了。。
