### ISSUE TITLE
高度不能自适应

### ISSUE THREAD

**Issue by wangrui460** [zhpanvip/BannerViewPager#83]
设置 BannerViewPager的高度是wrap_content，viewholder 是recyclerview，想要自适应，却发现高度一直是0，不显示viewholder，除非设置 BannerViewPager 的高度，才显示viewholder，即使这样，viewholder也不能自适应高度，只能自己计算~

**Comment by zhpanvip** [comment]
ViewPager其实也是没有自适应的，所以这个库也没有去计算。
