### ISSUE TITLE
ViewHolder getLayoutId add position or viewType as parameter

### ISSUE THREAD

**Issue by passid2019** [zhpanvip/BannerViewPager#87]
To allow different layout to be inflated depending on the position.
I suggest either passing viewType to getlayoutId and add an extra method in interface for delegating the recyclerView's getViewType(position).

**Comment by zhpanvip** [comment]
Thank you for your advice,It's will be supported in version 3.0.0

**Comment by zhpanvip** [comment]
V3.0.0 released
