### ISSUE TITLE
大哥圆角问题

### ISSUE THREAD

**Issue by yishangfei** [zhpanvip/BannerViewPager#88]
我写了一天 发现你这个库在我都项目中一直都不能圆角 ,    我在新项目把代码复制过去发现能用。。。这个改才能排查是什么导致的

**Comment by zhpanvip** [comment]
setRoundConer是给BannerViewPager设置圆角而并非是给item设置。如果你设置了MULTI_PAGE的页面样式，那么setRoundCorner是没作用的。这种情况下需要单独给item设置圆角。

**Comment by yishangfei** [comment]
![image](https://user-images.githubusercontent.com/15099278/77270765-d2512580-6ce7-11ea-9390-61d9718ecb33.png)
![image](https://user-images.githubusercontent.com/15099278/77270771-da10ca00-6ce7-11ea-9f83-6dc17b62ac17.png)
![image](https://user-images.githubusercontent.com/15099278/77270784-e4cb5f00-6ce7-11ea-85c3-fd57bbe8c884.png)
就是同样的这个代码放在我的现在开发的项目里不会有圆角，而我吧这套代码重新新建一个项目里面去运行就没有问题~

**Comment by zhpanvip** [comment]
你项目用的是CornerImageView吗？你加交流群吧，方便查看问题。
