### ISSUE TITLE
一屏多页问题，MULTI_PAGE_SCALE模式下两边不会漏出

### ISSUE THREAD

**Issue by startong** [zhpanvip/BannerViewPager#89]
测试了两款机型
荣耀V9，android 9 ，设置了app:bvp_reveal_width="16dp"，但是两边的item不会漏出来
荣耀畅玩7，android8，则正常

**Comment by startong** [comment]
刚刚又测试了一下，可能是屏幕分辨率不同导致的问题，当我设置成36dp时，荣耀v9可以漏出来了，但是畅玩7却漏出来了很多，
荣耀v9分辨率：2560x1440
荣耀畅玩7分辨率：1440x720
作者可以找机子试下，
那这个问题该如何解决啊

**Comment by startong** [comment]
![v9](https://user-images.githubusercontent.com/27007471/77217394-1bc13980-6b5d-11ea-8bf0-5f771fd36463.png)

这是荣耀v9 


![畅玩7](https://user-images.githubusercontent.com/27007471/77217400-2aa7ec00-6b5d-11ea-9130-cb0871b5a3cb.png)

这是荣耀畅玩7

**Comment by zhpanvip** [comment]
是否可以贴下代码？也可以加群交流

**Comment by startong** [comment]
> 是否可以贴下代码？也可以加群交流

![java代码](https://user-images.githubusercontent.com/27007471/77219649-b6784300-6b72-11ea-83ab-2cbcfe95a8d7.png)
![xml布局](https://user-images.githubusercontent.com/27007471/77219652-b8420680-6b72-11ea-82a8-a3963367f98a.png)
这是java代码和xml布局
加群了作者，麻烦通过一下哈

**Comment by zhpanvip** [comment]
通过setPageMargin与setRevealWidth调节间距大小。需要做屏幕适配。
