### ISSUE TITLE
希望把一些private的方法改成public

### ISSUE THREAD

**Issue by ljphawk** [zhpanvip/BannerViewPager#95]
比如获取adapter，获取ViewHolder，是否开启了自动轮播等等

**Comment by zhpanvip** [comment]
有什么必要的条件吗

**Comment by ljphawk** [comment]
有呀，比如判断当前是否设置了ViewHolder，是否已经开启了轮播

**Comment by zhpanvip** [comment]
如果未设置ViewHolder运行是会crash的，是否开启轮播是开发者自己设置的，也没必要在给开放出来了啊。

**Comment by zhpanvip** [comment]
3.0已发布，可以尝试升级到最新版本。
